### ISSUE TITLE
Ruins not coming through correctly in /v2/wvw/objectives

### ISSUE THREAD

**Issue by bherbst** [arenanet/api-cdi#102]
The ruin objectives do not appear to be coming through correctly in the objectives endpoint.

When I hit https://api.guildwars2.com/v2/wvw/objectives?page=0&page_size=200, I see five copies of the same objective for each map, each with different IDs but the same name and coordinates.

For example, there are five ruins objectives for "RedHome" that are each called "Demontrance Lake" and have the same coordinates in the middle of the lake, but they have different IDs.

**Comment by lye** [comment]
Erk, this is a content issue. The objectives don't actually have names internally -- the names are hardcoded into the event titles and on the sector label for the map. Looks like the ruins are not associated with the correct sectors right now :/

**Comment by lye** [comment]
This should be corrected.
