### ISSUE TITLE
/v2/wvw/objectives for Desert Borderlands

### ISSUE THREAD

**Issue by thetoothpick** [arenanet/api-cdi#104]
Would it be possible to get a peek at the data from the /v2/wvw/objectives endpoint for the new Desert Borderlands map before Heart of Thorns launches?  The application I'm maintaining requires hard-coded position mappings that can't be pulled directly from the API, so it'd be awesome to get a look at the objective IDs and positions so I can update the application before Heart of Thorns launches.

**Comment by lye** [comment]
So fun story -- the ids are different from each of our development branches. They won't be assigned until we do a live build with the new borderlands. 

That said, [here's what's on the dev branch](https://gist.github.com/lye/8abc0e3f731edd9d7c00). The coordinates, at least, should be correct (though the Z coord looks horribly wrong to me, but I'm not sure).

**Comment by thetoothpick** [comment]
Is the second (map-internal) portion of the ID going to be the same on live?  If so, that should be enough for me to work with for now.  Thanks!

**Comment by lye** [comment]
Not sure what you mean by `map-internal`. The `map_id` and `sector_id` fields are subject to change, but the `coord` values should be the same.

**Comment by thetoothpick** [comment]
Yea, I was referring to the second portion of the objective ID, after the dash (i.e. the original objective ID):

> I made the objective ids be the concatenation of the map id and objective id just to make them unique.

If that objective ID is subject to change too, I'll hard-code them now, but avoid publishing my changes until HoT goes live so I can verify the IDs.

Thanks!
