### ISSUE TITLE
Add ability to retrieve mastery rank and mastery track progress

### ISSUE THREAD

**Issue by atomicptr** [arenanet/api-cdi#109]

**Comment by lye** [comment]
Dupe of #273, but the good news is that it's live! If a bit belated.

**Comment by atomicptr** [comment]
Technically #273 is a dupe of this one, but I'm happy it's live :).

**Comment by lye** [comment]
Hah fair. I was going through them newest -> oldest and associated the PR with the first that I saw. Whoops!

**Comment by milneti** [comment]
Actually #237 was meant to be able to access mastery level directly at v2/account.js so not completely a dupe :)

As in "account X has 100 mastery points earned and 94 mastery points spent (aka. level)" 

Is that possible to still add @lye I don't want to crawl the masteries endpoint to simply sum up the points if I don't care about the details.
