### ISSUE TITLE
Wrong icons in v1/item_details.json

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#111]
`v1/item_details.json` is returning wrong icons for some items, `v2/items` returns the correct ones (example: [v1](https://api.guildwars2.com/v1/item_details.json?item_id=70821) ([icon](https://render.guildwars2.com/file/BF7AF3A619956A11E50AE7CDCCA93F19B6F19DD4/960304.png)) vs [v2](https://api.guildwars2.com/v2/items/70821) ([icon](https://render.guildwars2.com/file/FBC6FAF308D2210DB8ECD552900435E50545B92E/1202067.png))).

**Comment by lye** [comment]
The v2 endpoint uses the default skin's icon rather than the item icon (which is no longer used by the game). This matches the in-game behavior.

Might fix it someday though >_>

**Comment by darthmaim** [comment]
You don't have to waste your time fixing old endpoints, knowing I can just show the skin icon is good enough for me.
