### ISSUE TITLE
/v2/characters/*** bug

### ISSUE THREAD

**Issue by JoluMarti** [arenanet/api-cdi#116]
I'm getting this error.

This XML file does not appear to have any style information associated with it. The document tree is shown below.

    <Error code="48" module="3" line="389" text="callback (): Error: inventory not emptied! sparsify failure [{"id":21043,"slot":257,"count":1,"binding":"Character"},{"id":8941,"slot":265,"count":1},{"id":23031,"slot":266,"count":1},{"id":15188,"slot":269,"count":1},{"id":19980,"slot":270,"count":1},{"id":24581,"slot":277,"count":1},{"id":23038,"slot":279,"count":1},{"id":20316,"slot":283,"count":1},{"id":20686,"slot":318,"count":1},{"id":13858,"slot":322,"count":1},{"id":28608,"slot":323,"count":1,"upgrades":[24557]},{"id":38132,"slot":338,"count":2},{"id":38209,"slot":344,"count":1}] Error: inventory not emptied! sparsify failure [{"id":21043,"slot":257,"count":1,"binding":"Character"},{"id":8941,"slot":265,"count":1},{"id":23031,"slot":266,"count":1},{"id":15188,"slot":269,"count":1},{"id":19980,"slot":270,"count":1},{"id":24581,"slot":277,"count":1},{"id":23038,"slot":279,"count":1},{"id":20316,"slot":283,"count":1},{"id":20686,"slot":318,"count":1},{"id":13858,"slot":322,"count":1},{"id":28608,"slot":323,"count":1,"upgrades":[24557]},{"id":38132,"slot":338,"count":2},{"id":38209,"slot":344,"count":1}] at c:\arenanet\lliveweb.327\web\js2api\code\v2\controllers\account\characters.js:123:23 at c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:52:16 at c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:363:13 at c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:52:16 at done (c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:248:21) at c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:44:16 at c:\arenanet\lliveweb.327\web\js2api\node_modules\async\lib\async.js:360:17 at c:\arenanet\lliveweb.327\web\js2api\code\v2\controllers\account\characters.js:58:24 at c:\arenanet\lliveweb.327\web\js2api\code\v2\lib\memoize.js:34:24 at c:\arenanet\lliveweb.327\web\jssrv2\code\caches\remote.js:88:13"/>

**Comment by lye** [comment]
Oh god that's really not a good sign.

Can you email the offending API key to lawton@arena.net?

**Comment by Eearslya** [comment]
Wait, when did binding sneak its way into the API? How did I miss this?

**Comment by lye** [comment]
Posted #108 a couple months ago :>

Turns out it introduced a handful of pretty catastrophic bugs that didn't turn up in testing though. The most confusing part is that, by all accounts, the world should have burned down. I'm really not sure why this issue does not seem more widespread.

**Comment by lye** [comment]
So to follow up, I wasn't able to get the fix out in time for a hotfix; it should be going out with the Dec. 1st release.

**Comment by lye** [comment]
This should maybe be fixed on live -- wasn't ever able to repro in a dev environment, but fixed what I believe was causing the issue.
