### ISSUE TITLE
WvW Objective Upgrade Status

### ISSUE THREAD

**Issue by thetoothpick** [arenanet/api-cdi#118]
Hello,

Would it be possible to get the upgrade status (tier 0/1/2/3) of objectives in WvW (as part of /v2/wvw/matches)?  The upgrades are based on timers now, so they can be _loosely_ calculated based on time captured, but they're also affected by incoming dolyaks, which reduce the timer.  So it'd be useful to get the definite status from the API.

It would also be helpful to get the estimated time of the next upgrade (which would be updated as dolyaks come in), if it's possible.

Something like this:

```
"objectives":[
    {
        "id": "1099-99",
        "type": "Camp",
        "owner": "Red",
        "last_flipped": "2015-11-20T02:51:21Z",
        "claimed_by": "07605FAA-7629-482E-B4AC-4AE673EC0ECE",
        "claimed_at": "2015-11-20T04:19:01Z",
        "upgrades": 0, // or "None"
        "next_upgrade_at": "2015-11-20T03:21:21Z"
    },
    {
        "id": "1099-100",
        "type": "Camp",
        "owner": "Blue",
        "last_flipped": "2015-11-20T04:23:04Z",
        "claimed_by": null,
        "claimed_at": null,
        "upgrades": 3, // or "Tier3" or something
        "next_upgrade_at": null
    },
    ...
]
```

Thanks!

**Comment by lye** [comment]
Yeah, can definitely look into it.

I know the WvW API server has access to the current upgrades, but I'm not sure what the status of upgrade progress is -- if that's not already passed around it might not be very feasible to expose. I also want to expose which guild upgrades are slotted (if any) in each objective, but that's going to take awhile to get out.

**Comment by thetoothpick** [comment]
Any update on this?  The objective upgrades have been changed to be dolyak-based instead of time-based, so it'd be helpful to get the number of dolyaks delivered / remaining too.

**Comment by lye** [comment]
It's still on the backlog; I need a more detailed way of prioritizing tickets I guess.

WvW is probably the next area I'm going to be working on after I finish up with the remainder of the PvP endpoint stuff (and some minor guild endpoint changes). Not sure how long they changes will take to implement, but it's fairly high up on the order of things to do, so there's that at least :<

**Comment by Rwfrk** [comment]
It'd be nice if this were re-prioritized based on the new scoring based on objective tier.

**Comment by lye** [comment]
At long last I think all the bits off this have been implemented.
