### ISSUE TITLE
Can't request equipment with builds permission from equipment endpoint

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#122]
Requesting `/v2/characters/:name` contains equipment if the API key has the `builds` permission, but requesting `/v2/characters/:name/equipment` returns the error `requires scope inventories`.

**Comment by lye** [comment]
Whoops, yeah. Fix for that will go out the next time we do a deploy.

**Comment by lye** [comment]
Forgot to close the issue, but this should be fixed.
