### ISSUE TITLE
Achievement category and group endpoints don't support localization

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#124]
Both `/v2/achievements/categories` and `/v2/achievements/groups` always return all strings in english. The `Content-Language` header is set correctly, just the JSON is not localized.

**Comment by lye** [comment]
It wouldn't be an API release without stupid mistakes and a 5PM live deploy.

I'll have that fixed later this week; thanks for the heads up.

**Comment by lye** [comment]
Should be fixed.

**Comment by darthmaim** [comment]
:+1:
