### ISSUE TITLE
Gathering skins don't work in /v1/skin_details.json

### ISSUE THREAD

**Issue by StevenLiekens** [arenanet/api-cdi#126]
Skins with type: `gathering` return `ErrBadParam` in version 1 of the skins API.

v1
- https://api.guildwars2.com/v1/skin_details.json?skin_id=6055
- https://api.guildwars2.com/v1/skin_details.json?skin_id=6063
- https://api.guildwars2.com/v1/skin_details.json?skin_id=6075

v2
- https://api.guildwars2.com/v2/skins?ids=6055,6063,6075

**Comment by lye** [comment]
That's super weird; I'll have to look into why that's happening tomorrow. As always, thanks for the report!

**Comment by queicherius** [comment]
This is already fixed @lye 👍
