### ISSUE TITLE
Implement a local API for obtaining real-time data.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#127]
This supercedes #98; figured I'd make a new issue since we're not going to touch the MumbleLink stuff. I'm not sure if we'll honestly ever get around to implementing this, but here's the issue for posterity.

**Comment by lye** [comment]
After an initial investigation, [I found some issues](https://gitter.im/arenanet/api-cdi?at=571558ce4c2125fc3f03816c) with my proposed implementation. Basically, (1) the client can't service websockets over TLS locally (it has no key/cert), and (2) [HTTPS sites can't access non-TLS websockets](https://bugs.chromium.org/p/chromium/issues/detail?id=418482) (even if they're on localhost) because of the spec.

rip the dream.

If anyone has suggestions for alternatives which don't involve embedding a TLS key in the client (or using a TLS oracle [ala CF](https://blog.cloudflare.com/keyless-ssl-the-nitty-gritty-technical-details/)) let me know because :disappointed:

**Comment by Aralicia** [comment]
Probably really dumb suggestion (just woke up, so not completely up to par) : If you service a localhost-only, Non-TLS Websocket, could the community come up with a companion application working as bridge between the localhost-only websocket and a secure websocket ?

**Comment by lye** [comment]
Probably. One possible additional alternative (the recommended solution) is to use browser plugins to broker the connection. Both are really gross compared to just opening a webpage, so I definitely want to spend a bit of time looking into alternatives (the WebRTC suggestion was a good one). I don't want this to be a UX disaster for either developers or users.

**Comment by zeeZ** [comment]
WebRTC requires signaling though, so we're back at the insecure content issue. An official API that the client and sites use to do that? WebRTC also somewhat limits the browsers that can be used.

IMHO at this point a distinction should be made between a **local** API and a **web** API for real-time data and not force the former to become the latter.

**Comment by Aonwy** [comment]
Closing for organizational reasons. If there is some work needed here, please create a new ticket.
