### ISSUE TITLE
Scribe recipes not in /v2/recipes and outputs aren't in /v2/items.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#129]
For some reason, no scribe recipe is making it to `/v2/recipes` (and likewise, items that are directly deposited to the guild aren't showing up in `/v2/items`).

Forum references:
 * [Missing scribe recipes](https://forum-en.guildwars2.com/forum/community/api/API-Scribes-and-update-old-craft).

**Comment by darthmaim** [comment]
> no scribe recipe is making it to /v2/recipes

Some are there, example: https://api.guildwars2.com/v2/recipes/10238
