### ISSUE TITLE
Missing information to calculate total AP / missing achievements

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#138]
One of my users with a lot of AP was so friendly to [compile a list](https://www.reddit.com/r/gw2efficiency/comments/3w5s6f/list_of_achievement_ui_bugs/) and was ok with me crossposting them here. 

- Daily / monthly AP (and daily completion status) are missing
- No markers for repeatable achievements
- Missing achievements:
	- Hero achievements (1st, 2nd and 3rd birthday achievement missing)
	- Hall of Monuments ("God walking amongst mere mortals" achievement missing)
	- Tangled Depths (4 achievements missing, the 4 hidden ones)
	- Basic Collections (41 of 68 in the API)
	- Rare Collections (9 of 16 in the API)
	- Black Lion Collections (0 of 27 in the API)
	- Legendary Weapons (23 of 72 in the API)
	- Edge of the Mist (15 of 20 in the API)
	- Boss Week (6 of 7 in the API)
	- Retired Achievements (3 of 6 in the API)
	- 6 out of 37 historical achievement categories missing entirely (Blood and Madness 2013 and 2014, A very marry Wintersday 2013 and 2014 and Shadow of the Mad King 2012 and 2015)
	- Escape from Lion's Arch (15 out of 20 in the API, the 5 repeatables are missing)
	- Queen Jennah's Jubilee (13 out of 14 in the API, Opening Ceremony Attendee missing)
	- Support Evon Gnashblade (11 out of 12 in the API, repeatable minigame achievements missing)
	- Support Ellen Kiel (11 out of 12 in the API, repeatable minigame achievements missing)

A lot of the missing achievements are the one's which are hidden until unlocked.

**Comment by lye** [comment]
> Daily / monthly AP (and daily completion status) are missing

Hmm, I'm not sure where those are stored, actually. Will have to investigate -- they're probably just a counter somewhere. It may make sense to throw an object onto `/v2/account`'s response that has an AP overview (and includes daily/monthly counts).

> No markers for repeatable achievements

Ick, I'll have to add those in. The repeatable achievements are also missing a prerequisite achievement which would be useful with the data.

> Missing achievements

Most of those should be sorted out sometime after the next release. I added in a whitelist system (similar to the item/skin/recipe/etc bits) which watches the logs for achievement progress events and persists the list of achievement ids seen. That way we can track which achievements are actually acquirable and avoid dumping a bunch of debug/testing/in-dev achievements onto the endpoint.

**Comment by lye** [comment]
Okay, all of the bits and pieces for this should be inplace. Let me know if there's something I missed.
