### ISSUE TITLE
Missing icon in the /v2/guild/ranks API

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#148]
The "sun" rank icon is missing:

![](http://i.imgur.com/Zh05DYG.png)

```js
{
"id": "One",
"order": 3,
"permissions": []
},
```

**Comment by lye** [comment]
```js
return {
    // ...
    icon_id : parseInt(rankIdStr, 10) || undefined;
    // ...
}
```

Which which id that icon has? :tangerine:  

I'll see if I can push out the fix tomorrow (not feeling up for a 5PM deploy today).

**Comment by queicherius** [comment]
Hah, sometimes the unexpected `0` behaves like the expected `NaN` :smiley:. Yeah, no rush with that. Just thought i'd let you know.

**Comment by lye** [comment]
Well.

@queicherius I either just deployed the fix and it worked, or all of the `icon` fields are now `null`.

**Comment by lye** [comment]
Okay, created a guild on live and [confirmed that the fix works](https://api.guildwars2.com/v2/guild/699464D3-01A9-E511-80D4-E4115BEBA648/ranks?access_token=40EAB095-8F22-9642-A6FB-C84ADA2C6A16C51F0AFA-03ED-4698-9630-9E83C08AA017). What an afternoon.

**Comment by queicherius** [comment]
> @queicherius I either just deployed the fix and it worked, or all of the icon fields are now null.

["Move fast and break things"](https://imgs.xkcd.com/comics/move_fast_and_break_things.png) :laughing: 

> Okay, created a guild on live and confirmed that the fix works. What an afternoon.

Can confirm too, that was quick, thanks! :+1:
