### ISSUE TITLE
/v2/quaggans does not return X-Result-Total

### ISSUE THREAD

**Issue by StevenLiekens** [arenanet/api-cdi#15]
Example request: https://api.guildwars2.com/v2/quaggans?ids=summer,vacation

Actual response headers

> HTTP/1.1 200 OK
> Content-Type: application/json; charset=utf-8
> Content-Encoding: gzip
> Content-Language: en
> Vary: Accept-Encoding
> Server: Microsoft-IIS/7.5
> X-Result-Count: 2
> Access-Control-Allow-Origin: *
> X-Content-Type-Options: nosniff
> Date: Tue, 03 Mar 2015 19:12:37 GMT
> Content-Length: 107

Expected response headers
> HTTP/1.1 200 OK
> ...
> X-Result-Count: 2
> X-Result-Total: 35

**Comment by lye** [comment]
`X-Page-Total`, `X-Page-Size` and `X-Result-Total` are only returned when paginating the results, e.g. `https://api.guildwars2.com/v2/quaggans?page=0`. This should be true for all bulk-expanded endpoints, not just `/v2/quaggans`.

**Comment by StevenLiekens** [comment]
Is that how it's always been? I'm pretty sure that I remember there being a `Total` header for bulk requests.

**Comment by lye** [comment]
I may have broken things a couple of weeks ago. Now that I've had some coffee, it makes sense that `X-Result-Total` would be sent with all bulk-expanded responses.

**Comment by lye** [comment]
The fix for this is now deployed (whoo!)
