### ISSUE TITLE
Skin rarity

### ISSUE THREAD

**Issue by BryghtShadow** [arenanet/api-cdi#156]
These skins have orange names in-game, but there is no rarity field in the API.
https://api.guildwars2.com/v2/skins?ids=6059,6360,6183,6418,6043,6050,6375,6479,6350

**Comment by lye** [comment]
AFAIK no skins have an associated rarity. Rarity is an item attribute.

**Comment by lye** [comment]
Apparently pre-coffee I am literally blind. There totally is a rarity field, how did I miss that.
