### ISSUE TITLE
"Gilded Hollow" missing from floors 1, 2 and 3

### ISSUE THREAD

**Issue by FrederikNS** [arenanet/api-cdi#157]
The Gilded hollow is missing from the floors 1, 2 and 3. I know it isn't layered like the other Maguuma zones, but it seems a bit odd that it's missing, as all the vanilla zones are present on all the floors.

I asked this question as part of #153, but it seemed people missed it, so I decided to extract it to its own issue.

**Comment by lye** [comment]
So, the extra 1,2,3 floors were being injected by the content layer; finally managed to track that down. The [gilded hollow maps](https://api.guildwars2.com/v2/maps?ids=1101,1107,1108,1121,1125) are now only on floor 0.
