### ISSUE TITLE
/v2/skills missing locale aware flag in /v2 and /v2.json

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#164]
/v2/skills is missing the locale aware flag in [/v2](https://api.guildwars2.com/v2) and [/v2.json](https://api.guildwars2.com/v2.json). For example: [Bandage](https://api.guildwars2.com/v2/skills/1175) / [包扎](https://api.guildwars2.com/v2/skills/1175?lang=zh).

**Comment by lye** [comment]
Thanks for the report! That should be fixed the next time I do a deploy (maybe later this week).

**Comment by lye** [comment]
Deployed!
