### ISSUE TITLE
Chat link headers changed

### ISSUE THREAD

**Issue by StevenLiekens** [arenanet/api-cdi#166]
The header bytes for chat links have changed in a recent game client update. Affected chat link types include skills, traits, recipes, skins and outfits. The result is that `chat_link` values in /v2/recipes are now interpreted as skin chat links by the game client.

I believe someone deserves to be slapped across the face with a wet fish for changing the headers.

**Comment by lye** [comment]
Wiki values are up-to-date. Updated the copy of the enumeration values in the API code; fix for `/v2/skills` and `/v2/recipes` should go out with the next deploy (later this week?)

**Comment by lye** [comment]
The fix for this should be live!
