### ISSUE TITLE
General Guild info

### ISSUE THREAD

**Issue by Fishrock123** [arenanet/api-cdi#169]
Opening this up to track some things @lye mentioned to me the other day, since there is currently no issue/pr for "general" guild info.

This general info consists of:
- [ ] Guild Emblem
- [ ] Guild MOTD (Message of the day)
- [ ] Guild Currencies
- ?

**Comment by FreezyExp** [comment]
motd is in the guild log
emblem is in v2\guild\the :id 
you can find a renderer for the data online

**Comment by lye** [comment]
These should all be done since awhile back; they're all part of the authenticated `/v2/guild` endpoint.

**Comment by Fishrock123** [comment]
Oh, sweet!
