### ISSUE TITLE
Access-Control-Expose-Headers CORS header is malformed

### ISSUE THREAD

**Issue by poke** [arenanet/api-cdi#170]
Currently, the following CORS headers are returned:

```
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: "Link, X-Page-Total, X-Page-Size, X-Result-Total, X-Result-Count"
```

Those quotes are misplaced there, making it impossible to retrieve either header via CORS requests. The correct response should be the following (without quotes):

```
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link, X-Page-Total, X-Page-Size, X-Result-Total, X-Result-Count
```

**Comment by tivac** [comment]
:wrench: Fixed on dev

- `Access-Control-Expose-Headers` is no longer quoted
- `Cache-Control` is no longer quoted
- `Expires` has a valid RFC 7231 timestamp again

**Comment by lye** [comment]
Deployed!
