### ISSUE TITLE
Scribe recipes with missing items from ingredients

### ISSUE THREAD

**Issue by BryghtShadow** [arenanet/api-cdi#174]
There are scribe recipes that are built using items in guild storage (namely banners and decorations). However, these items are missing from the `ingredients` array.
* Out of 408 Scribe recipes, there are 176 recipes that are built from items in guild storage: https://api.guildwars2.com/v2/recipes?ids=9917,9919,9926,9928,9938,9941,9959,9975,9979,9983,9985,10004,10006,10008,10014,10030,10037,10038,10049,10060,10071,10072,10076,10081,10084,10087,10097,10101,10103,10106,10113,10129,10142,10152,10168,10180,10183,10199,10217,10237,10257,10258,10260,10263,10265,10293,10294,10356,10357,10360,10371,10383,10391,10395,10402,10412,10423,10431,10434,10461,10462,10470,10475,10479,10482,10499,10510,10521,10530,10557,10565,10566,10567,10579,10599,10601,10622,10626,10635,10643,10646,10669,10686,10691,10693,10714,10765,10785,10790,10801,10810,10812,10821,10856,10867,10870,10887,10893,10921,10928,10965,10968,10977,10994,11009,11022,11024,11030,11031,11086,11099,11103,11113,11119,11135,11145,11148,11149,11151,11163,11174,11185,11186,11220,11246,11257,11261,11287,11301,11306,11318,11319,11320,11323,11326,11337,11339,11345,11374,11383,11430,11452,11457,11460,11469,11475,11489,11495,11503,11511,11513,11528,11530,11537,11538,11563,11582,11591,11594,11609,11635,11636,11637,11645,11672,11674,11691,11702,11709,11727,11734,11746,11750,11752,11753,11754
* Out of the above 176 recipes, 172 have type `"GuildDecoration"`; the other 4 (`[10168,11009,11185,11563]`) have type `"GuildConsumable"`.

## Example
https://api.guildwars2.com/v2/recipes/10183
```json
{
  "type": "GuildDecoration",
  "output_item_id": 71716,
  "output_item_count": 1,
  "min_rating": 125,
  "time_to_craft_ms": 1000,
  "disciplines": [ "Scribe" ],
  "flags": [ "AutoLearned" ],
  "ingredients": [
    { "item_id": 70454, "count": 1 },
    { "item_id": 75087, "count": 1 },
    { "item_id": 19713, "count": 5 }
  ],
  "id": 10183,
  "chat_link": "[&CccnAAA=]"
}
```
Ingredients should be:
* 1 Basic Finishing Kit (id: `70454`)
* 1 Essence of Elegance (id: `75087`)
* 5 Soft Wood Planks (id `19713`)
* 1 Highback Chair (id: `75298`)

**Comment by lye** [comment]
Ah, hmm, normally the action of whitelisting a recipe also whitelists all ingredients. Scribe's a bit special, so I presume that it behaves differently. I'll see if I can draft a script that enumerates the current state so I can one-off whitelist everything that's missing.

Thanks for the report!

**Comment by BryghtShadow** [comment]
Does the guild storage use a different `item_id` compared to the `output_item_id` in recipes? (I wish I could link items in the guild storage)

**Comment by lye** [comment]
The "items" output by scribe recipes that go into the guild inventory aren't actually items -- they're guild upgrade objects (e.g., the id references `/v2/guild/upgrades`).

**Comment by darthmaim** [comment]
Probably too late to change the ingredients/output to the same data structure as objectives/rewards of achievements (`{type: "awesome", id: 42, count: 1}`). /v2/recipez plz.
