### ISSUE TITLE
an item without name

### ISSUE THREAD

**Issue by jligeza** [arenanet/api-cdi#179]
This record has no 'name' key in dict: https://api.guildwars2.com/v2/items/70994

**Comment by darthmaim** [comment]
Here are some more items with no name: https://api.guildwars2.com/v2/items?ids=63366,70994,71093,71914,72587,72700,72726,72897,72971,73746,74126,76651

**Comment by lye** [comment]
Hmm, I can default the `name` field to an empty string. I suspect that those items were either broken to begin with, or deprecated (e.g., replaced with a new item when you log in). I should find some way to put the deprecation status in the endpoint response.

**Comment by lye** [comment]
Yep, all of those items have no name in content -- looks like they weren't ever obtainable (maybe?). I don't see a deprecation entry or anything for 'em though.

Changed it to default `name` to `""` in this case.

**Comment by lye** [comment]
And deployed.
