### ISSUE TITLE
Shared inventory slots

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#180]
With the new addition of shared inventory slots it would be cool if we could get the contents of them too. 

Not sure what the best format for that would be, I can think of either putting them into `/characters` with a special key or as another field in `/account`. Or a new endpoint entirely?

**Comment by darthmaim** [comment]
> **lye** Jan. 12 21:27
> hmm, I guess I should add /v2/account/inventory

https://gitter.im/arenanet/api-cdi?at=569561c1b1f439094a07c3e1

**Comment by queicherius** [comment]
I knew I read that somewhere, I just couldn't place it anymore. Oh well, now we have an issue for it. :smile:

**Comment by lye** [comment]
Deployed! [demo](https://api.guildwars2.com/v2/account/inventory?access_token=1B410E2E-DECA-D248-9354-82724F218D753D7EAAC2-BBC8-4051-9AEB-FD3DEC6BD0FF).
