### ISSUE TITLE
TypeError: "slot" of undefined / ErrUnknown

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#194]
One of my users reported this error to me:
- [The materials page](https://api.guildwars2.com/v2/account/materials?access_token=BBF2FCF5-CF25-F449-8044-6EFF2F77EA60CC7D9688-A2BC-4686-A681-A4E7D2431E3E) throws [ErrUnknown](http://imgur.com/RnbawnX)
- [The characters endpoint](https://api.guildwars2.com/v2/characters?page=0&page_size=200&access_token=BBF2FCF5-CF25-F449-8044-6EFF2F77EA60CC7D9688-A2BC-4686-A681-A4E7D2431E3E) throws [Type Error: Cannot read property slot of undefined](http://i.imgur.com/G3B5uKY.jpg)

I personally don't get the errors when visiting the pages, my guess is it might be data-center specific (he is on NA servers, I am in the EU)? Then again he tried to use a VPN from Germany, and it still didn't work.

**Comment by lye** [comment]
I can't repro this at all on either datacenter -- both requests seem to work fine for me.

Historically, the component which reads in account/character data has been a bit flaky, so I'm assuming there was a transient failure which has since been resolved? The characters one is probably a bug in the error handling -- I'll see if I can make it fail a bit more cleanly.

**Comment by queicherius** [comment]
> The problem is I can access 100% on my cell phone(android / any web browser), but cannot do anything on my PC (I have 4 PC with different OS / components).

**Comment by lye** [comment]
Yeah, super weird. I'll fiddle with it some more next week and see if I can get a repro. It's definitely some kind of strange issue on our end, though I've no idea what it could be :/

**Comment by queicherius** [comment]
Another report on this. It's the material storage `ErrUnknown` again.

- I sent you the API key in private on gitter, but the request works for me and it throws `ErrUnknown` for the user, on all his devices
- **Country:** South Korea
- **Browser & OS:** Google Chrome / Windows8
- **ISP**: FTTH

**Comment by lye** [comment]
I've not a clue. The API keys works for me against both Dallas and Frankfurt; additionally I don't see anything in the logs for the account blob reader (other than `error: empty player blob` which this almost certainly isn't).

If possible, can you ask what `api.guildwars2.com` resolves to? Or if it happens in other browsers (or even in a private/incognito tab?). Or if they've logged into the game recently?

At this point, the most plausible explanation I have is that that error is cached somewhere (which is ... well the API is over SSL with cache headers that Chrome understands).

**Comment by queicherius** [comment]
Here are his answers:

- `api.guildwars2.com` resolves to `64.25.40.51`
- IE has the same issue
- He logs into the game every day

**Comment by lye** [comment]
Well, that's the Dallas datacenter so there's probably nothing too terrible going on.

I was really hoping for something different; I have no idea why the same request would give them different results. Color me completely confused :<

**Comment by queicherius** [comment]
So since there were no reports from any user in forever for this, I think this is resolved. 🎇
