### ISSUE TITLE
Mine upgrades not included in /v2/guild/:id/upgrades

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#196]
Looks like all the mine upgrades are missing. Everything else works as expected :)

![unbenannt](https://cloud.githubusercontent.com/assets/4615516/12541415/1d89f75e-c317-11e5-96c0-c4a2e85ba40f.png)

**Comment by lye** [comment]
The upgrades in `/v2/guild/:id/upgrades` are filtered by type; looks like I missed one. Should be an easy fix, will have it deployed later this week.
