### ISSUE TITLE
Broken Markup on german Authorization Page

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#20]
The german /oauth2/authorization page has broken html markup:

```html
<p>
    Die App <a href="http://gw2treasures.local/“>#TEST# GW2Treasures</a> möchte auf deinen
    <i>Guild Wars 2</i> Account zugreifen.<br>Wenn du den Zugriff gestattest,
    hat sie zu Folgendem ausschließlich Lesezugriff:
</p>
```

Notice the wrong quotation mark `“` in the href.

Broken:
![authorize_de_small](https://cloud.githubusercontent.com/assets/2511547/6764593/7b333918-cfb8-11e4-8551-426cbeae8d58.png)
Working:
![authorize_en_small](https://cloud.githubusercontent.com/assets/2511547/6764592/7b2edea4-cfb8-11e4-9daf-d231d808fea1.png)

**Comment by lye** [comment]
Whoops, I dropped the ball on that one. Will push out the fix later this week.

**Comment by lye** [comment]
And the fix is live!
