### ISSUE TITLE
/v2/skills -- some skill fact types are missing icons.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#200]
The pseudo-fact types (e.g., `range` and `combo_finisher`) all need to have the hardcoded UI icons added to them.

**Comment by ptolstoi** [comment]
The API misses all icons (facts and skill icon itself) at the moment e.g. [5497](https://api.guildwars2.com/v2/skills/5497)

**Comment by lye** [comment]
That should be fixed as-of the deploy I just did. I switched one of the backend's output formats for icons to match all of the other icon-emitting code (the skills stuff is fairly old); I had a patch for the API frontend that handled both old and new encodings but ... didn't deploy it before the release as I'd intended. Sorry about that! :<

**Comment by lye** [comment]
Also *all* skill fact types should now have an `icon` field, so closing this out.
