### ISSUE TITLE
Engineer pistol skill 1 flip_skill

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#201]
The Engineer's pistol skill 1 (Fragmentation Shot), which can be found at [`/v2/skills/5827`](https://api.guildwars2.com/v2/skills/5827), has a `flip_skill` with a value of `6042`.

[`/v2/skills/6042`](https://api.guildwars2.com/v2/skills/6042) is also Fragmentation Shot, but cannot be seen anywhere in the game at the moment (supposedly it was a traited skill which is not acquirable anymore).

I suppose the best option is to hide or remove it from `/v2/skills`.

**Comment by lye** [comment]
The flip skill is Fragmentation Shot when traited with [Ankle Shots](https://wiki.guildwars2.com/wiki/Ankle_Shots). The profession mismatch apparently isn't properly brushed under the rug when considering the `flip_skill` field.

**Comment by Archomeda** [comment]
I just checked the other Engineer pistol skills, and most of them are affected as well:
- Skill 2: Poison Dart Volley
- Skill 3: Static Shot
- Skill 4: Blowtorch (although with this one there seems to be two skills, like the others, but there's no `flip_skill` assigned)
- Skill 5: Glue Shot

**Comment by lye** [comment]
These should all be fixed.
