### ISSUE TITLE
Engineer pistol skill 1 finisher chance incorrect

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#202]
The Engineer's pistol skill 1 (Fragmentation Shot), which can be found at [`/v2/skills/5827`](https://api.guildwars2.com/v2/skills/5827), has a `ComboFinisher` fact with `percent: 100`.

If that was only true in-game. Sadly, the chance is only 20%.

I'm unsure if this skill is an isolated issue, or if there are more skills affected by this.

**Comment by lye** [comment]
There's going to be more skills affected by this -- there's multiple ways in content to indicate that a skill has a `ComboFinisher` fact. With the method this skill uses, there isn't an encoded `chance`, so the current code incorrectly assumes `100%`. I think there's a table somewhere with the correct chance values that I need to reference.

**Comment by lye** [comment]
All of the "20% chance projectile finisher" facts should now be rendered correctly!
