### ISSUE TITLE
v2/wvw/matches possible bug

### ISSUE THREAD

**Issue by hdunderscore** [arenanet/api-cdi#216]
To counter the kills deaths dropped value issues (mentioned here: https://forum-en.guildwars2.com/forum/community/api/WvWvW-API/first#post5962863), I put together a simple server to keep track of the kills/deaths for every server.

The problem is there appears to be an issue where the NA and EU kills and deaths are mirrored, made very obvious when you sort by the KDR column here: http://tc-hdu.rhcloud.com/

Was the EU kills/deaths implemented?

Can anyone confirm the bug?

**Comment by antonbalboa** [comment]
If I rememeber well, the EU Kill/Deaths was not working when they introduced it (only NA worked). In forums some developer said was looking into it but it would take a lot of work to change this.

**Comment by lye** [comment]
That looks totally bugged to me. I'll try to dig around and see what's going on :(

**Comment by lye** [comment]
Missed the cutoff to get the fix into the next release; should be fixed in the one after. Sorry :(

**Comment by hdunderscore** [comment]
Thanks for taking a look !

**Comment by lye** [comment]
This should now be functioning properly (e.g., counters are properly segregated by datacenter).
