### ISSUE TITLE
/v2/characters can have invalid skin ids

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#218]
I ran into a bug, where the skin id provided for one of the character's equipment items is not valid.

``` js
{
  "id": 49878,
  "slot": "WeaponA1",
  "upgrades": [
    24618,
    24551
  ],
  "skin": 6069
}
```

https://api.guildwars2.com/v2/skins?ids=6069&lang=en says `all ids provided are invalid`.

If you need the API key I can PM it to you somewhere, it's from a user and I dont wanna publicly post it without permission.

**Comment by darthmaim** [comment]
The skin you posted is the default skin of [69974](https://api.guildwars2.com/v2/items/69974).

Here are some more skins that are missing from the API (265 total): [missing_skins.csv](https://gist.github.com/darthmaim/045813cbecc195a4f7d3) (either default_skin or details.skins of transmutations is missing)

**Comment by queicherius** [comment]
Oh, that's... :sob: 

I read through #155 but the ID wasn't in there so I didn't double check... guess I'll leave this open for now.

**Comment by lye** [comment]
I'll go through the `/v2/items` endpoint probably next week and whitelist all the `default_skins`. That should fix the issue (but might bring up other issues, hype).

**Comment by queicherius** [comment]
This issue fixed itself at some point when the whitelisting got in. :1st_place_medal:

**Comment by lye** [comment]
🎉
