### ISSUE TITLE
/v2/wvw/matches -- add oasis event timer

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#221]
Should track the last time an oasis event occurred and expose that per-match.

([forum thread](https://forum-en.guildwars2.com/forum/community/api/WvW-Oasis-PvE-event-API-to-create-timers))

**Comment by RaymondBakker** [comment]
Any updates on this?

**Comment by lye** [comment]
Haven't gotten around to it yet  :<

**Comment by RaymondBakker** [comment]
Anything yet? :8ball:

**Comment by tivac** [comment]
It's on the list, continual pinging will **not** speed up work.

**Comment by lye** [comment]
The event's [been removed](https://forum-en.guildwars2.com/forum/support/bugs/BUG-WvW-Guild-Challenge-Impossible/6030446) so closing this one out.
