### ISSUE TITLE
/v2/account/achievements - Missing completion status

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#223]
Some of the completion stati are still not showing up (nearly there!)

Examples for this is e.g. "Dragon Ball Champion" from the Lunar New Year achievements. [`1CF81DA0-65A3-B344-B96C-930BF4F21624E095F81F-46CB-4F1F-965D-677B2F03DB12`](https://api.guildwars2.com/v2/account/achievements?access_token=1CF81DA0-65A3-B344-B96C-930BF4F21624E095F81F-46CB-4F1F-965D-677B2F03DB12) has all AP for it in game, but the achievement `2804` doesn't show up in the completed list.

**Comment by lye** [comment]
For reasons that are beyond my understanding, the achievement whitelist process is currently broken. I'm not sure where things are breaking (and can't repro the issue on a dev environment), but I've been manually running queries against the historical logs to pull up missing achievements. I'll do another import now to grab the new missing LNY achievements.

:(

**Comment by queicherius** [comment]
No worries, with the last few updates its only a few points (~50 ish) off for most accounts. Thanks again for all in #138!

**Comment by Malediktus** [comment]
This issue affects me, too. But on a large extend than 50 AP.
GW2efficiency thinks I have 31.520 AP, but I have 31.994 ingame, so almost 500 AP missing (from repeatable achievements only it seems). I have all historic and not historic repeatable achievements maxed out, so maybe my API key helps:
EC70B07E-C889-4C44-81B8-D132C9D2CE1771B66784-DF47-4BC3-B154-3E60BE657158

**Comment by Malediktus** [comment]
I think I found the reason for the repeatable achievement bug. If I meet the exact criteria of a repeatable achievement, it does work. If it is for example at 1/5 it will work. But if it is at 0/5 it will not work. For some reason the API is not providing the completion status if you stop exactly at a checkpoint of a repeatble achievement.

**Comment by lye** [comment]
Just deployed the fix for the bug -- repeated achievements with no progress towards the current iteration should now be appearing correctly. Going to close this out for now; let me know if you find further issues! (there are probably further issues).
