### ISSUE TITLE
Fully qualified paths not working for pvp/games and pvp/seasons

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#225]
According to [v2](https://api.guildwars2.com/v2), the IDs returned by an endpoint can be used to create a fully qualified path. This works for most endpoints, but not for `pvp/games` and `pvp/seasons`.

For example:
[v2/pvp/seasons](https://api.guildwars2.com/v2/pvp/seasons) returns just one ID: `44B85826-B5ED-4890-8C77-82DDF9F2CF2B`
[v2/pvp/seasons/:id](
https://api.guildwars2.com/v2/pvp/seasons/44B85826-B5ED-4890-8C77-82DDF9F2CF2B) gives a 404
[v2/pvp/seasons?id=:id](
https://api.guildwars2.com/v2/pvp/seasons?id=44B85826-B5ED-4890-8C77-82DDF9F2CF2B) works

**Comment by lye** [comment]
Ah yeah, thanks for opening this; had totally forgotten. I should have the fix for this deployed today or tomorrow.

**Comment by lye** [comment]
Deployed!
