### ISSUE TITLE
/v2/commerce/exchange is throwing "ErrBadParam"

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#231]
[The "gems" endpoint](https://api.guildwars2.com/v2/commerce/exchange/gems?quantity=1000000) as well as [the "coins" endpoint](https://api.guildwars2.com/v2/commerce/exchange/coins?quantity=1000000) throw the following error:

```js
{
  "text": "ErrBadParam"
}
```

**Comment by lye** [comment]
Just deployed the fix, sorry 'bout that!
