### ISSUE TITLE
Daily achievement 2817 doesn't exist

### ISSUE THREAD

**Issue by robertluedke** [arenanet/api-cdi#236]
Achievement 2817 got it into the daily PvP achievements today, but
https://api.guildwars2.com/v2/achievements/2817
only returns:
{"text":"no such id"}

**Comment by darthmaim** [comment]
If I remember correctly the achievements are only whitelisted once per day, so it might take some time for new achievements to appear.

**Comment by robertluedke** [comment]
If this is true, this is bad practice. You cannot say, you'll get some great stuff in this house, but you have to wait until it is build... Instead you shouldn't say something about it or better do some preparations to be sure, it is there, when the time will come, when it is needed. :D

**Comment by tivac** [comment]
Dunno if this is a whitelisting issue, I'll see if I can find out.

@robertluedke Disagree. We use whitelisting to prevent accidentally leaking unreleased information via APIs. You may not like it but it doesn't make it a bad practice.

**Comment by robertluedke** [comment]
Yeah, @tivac I agree with you. Whitelisting to prevent leaking is fine, but it should be working also on day 1 for a new one, not that the whitelisting happens so much later after pointing to this data somewhere else. That's all, what I wanna say. :)

**Comment by darthmaim** [comment]
Just found [the source](https://forum-en.guildwars2.com/forum/community/api/Daily-achievement-missing/6003020) for my comment above:

> I think that was a cache issue — the daily achievements are automatically whitelisted (they bypass the normal manual approval). The master list of whitelisted achievements was probably just cached for a while after reset (it’s got a fairly long cache duration since it only updates once/day at most — since usually it’s a manual process).
IIRC this happened because there were new dailies released yesterday, so this shouldn’t happen too frequently.

**Comment by lye** [comment]
Sorry! Been out all week and haven't been attending to the whitelist queue. Just whitelisted this achievement :>

**Comment by robertluedke** [comment]
Thank you, very much! :)
