### ISSUE TITLE
/v2/guild/:id/log - kicked members don't have names

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#238]
In the guild log, log entries that involve a kicked member don't have the member name (since the name resolution uses the guild member list). Whoops.

([forum thread](https://forum-en.guildwars2.com/forum/community/api/guild-log-Kick-events-with-no-user-details))

**Comment by idivait** [comment]
Yay! I've been working on some Slack integrations based on the /v2/guild/:id/log API (Did a nifty little ./motd node api. (http://puu.sh/ntTxC/cec252ab4b.png) ... I'd been planning to expand it with a kick notification to the officer channel, but the non-names made that idea kind of pointless.
