### ISSUE TITLE
Support empty parameters

### ISSUE THREAD

**Issue by StevenLiekens** [arenanet/api-cdi#24]
I think that bulk expanded endpoints are broken in the sense that an empty `ids` parameter is treated as if there was no query string at all.

An example...
````
https://api.guildwars2.com/v2/items?ids=
````

Is treated the same as...
````
https://api.guildwars2.com/v2/items
````

When I visit that first URL, I would expect one of two things:
* An error response, content set to `{"text":"no ids provided"}`
* A success response, content set to `[]`

Instead, the API returns an array of numeric values, when my program is expecting an array of objects.

**Comment by lye** [comment]
Seems reasonable enough to me. I'll make the change unless there's dissent, not sure when it'll go out though.

**Comment by StevenLiekens** [comment]
Thanks! By the way, I think the same issue applies to pagination.

````
https://api.guildwars2.com/v2/items?page=
````

**Comment by tivac** [comment]
This is written, pending code review from @lye. Both `?ids=` and `?page=` return a `HTTP 400`.

**Comment by StevenLiekens** [comment]
Sweet :)

What about `id=`?

**Comment by tivac** [comment]
Good catch! `?id=` returns `HTTP 400` as well. @lye signed off, so checking this into dev.

**Comment by lye** [comment]
This is now live, as of this morning.
