### ISSUE TITLE
Flask of Pumpkin Oil doesnt have correct duration

### ISSUE THREAD

**Issue by windwarrior** [arenanet/api-cdi#245]
https://api.guildwars2.com/v2/items/67371 lists the duration as 0ms, that is probably an error :).

**Comment by lye** [comment]
Hmm, zero is what's in the item's tooltip. Those will have to be individually fixed in content -- could you get me a list of all the affected IDs? I might be able to write a script to pull the parameter from the on-use scripts.

**Comment by BryghtShadow** [comment]
Related to incorrect durations, Anguished Tear of Alba ([item #70596](https://api.guildwars2.com/v2/items/70596)) shows the wrong duration.

Item grants 2 buffs: "Anguished Tear of Alba" (effect #33164) with 1800000 ms duration and "Fractal Defensive" (effect #32134) with 3600000 ms duration.

However, Tooltip and API only lists one buff: "Anguished Tear of Alba" with 3600000 ms duration.

**Comment by BryghtShadow** [comment]
https://api.guildwars2.com/v2/items?ids=67368,67371 are the only items currently that have 0 duration in the API as well as the tooltip.

**Comment by lye** [comment]
The pumpkin flash fix went out. I created a new issue for the Anguished Tears of Alba; totally missed that. These are all content changes (i.e., it affects the in-game tooltips too, not just the API) so it takes me awhile to get 'em fixed.
