### ISSUE TITLE
/v2/items missing buff name

### ISSUE THREAD

**Issue by BryghtShadow** [arenanet/api-cdi#246]
Consumables that grant an effect (usually a nourishment of some sort) lacks the name of the buff. e.g. e.g. [Flask of Pumpkin Oil](https://api.guildwars2.com/v2/items/67371) grants `Pumpkin's Blessing`, while [Rough Sharpening Stone](https://api.guildwars2.com/v2/items/9431) grants `Nourishment`.

**Comment by lye** [comment]
I've added in `.details.name` and `.details.icon` for `Consumable` type items that provide buffs. Should go out at some point.

**Comment by lye** [comment]
Fix should be deployed.
