### ISSUE TITLE
Expose guild missions (/v2/guild/missions and /v2/guild/:id/missions).

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#247]
Not sure how feasible this is.

([forum ref](https://forum-en.guildwars2.com/forum/community/api/Access-to-guild-mission-list))

**Comment by darthmaim** [comment]
@Aonwy Why exactly was this closed?

**Comment by ChieftainAlex** [comment]
Might as well have a link to a working forum ref:

https://forum-en.gw2archive.eu/forum/community/api/Access-to-guild-mission-list

**Comment by Aonwy** [comment]
This was closed due to the age of the ticket and lack of activity on the forum and here. I'll leave the new ticket open.
