### ISSUE TITLE
skills.transform_skills returns unknown skill ids

### ISSUE THREAD

**Issue by Aralicia** [arenanet/api-cdi#254]
Querying `Elixir X` data gives the following ids in transform_skills : `[5752,5753,5754,14485,14488,14489,14556,14490]` (https://api.guildwars2.com/v2/skills?id=5832).

While the ids 5752, 5753 and 5754 refers to known skills, 14485 and up are unknown and not queryable through the API.

**Comment by lye** [comment]
Also bundle skills are totally busted.

**Comment by lye** [comment]
This should be fixed since awhile ago.
