### ISSUE TITLE
/v2/pvp shouldn't require authentication

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#259]
Currently /v2/pvp requires authentication, but only returns a (incomplete) list of subendpoints and no user specific data.

```js
module.exports.index = troll(
    token.requireScopes([ "account", "pvp" ]),

    function(req) {
        return reply.json([
            "stats",
            "games"
        ]);
    }
);
```

gitter discussion starting at https://gitter.im/arenanet/api-cdi?at=56e1de273194fbd11095f65c

**Comment by tivac** [comment]
Fixed on dev.

**Comment by lye** [comment]
Thanks @tivac !
