### ISSUE TITLE
/v2/commerce/exchange/coins return "ErrUnknown"

### ISSUE THREAD

**Issue by Teranas** [arenanet/api-cdi#267]
Hi,

it seems like /v2/commerce/exchange/coins is broken. It returns:

`{"text":"ErrUnknown"}`

See: https://api.guildwars2.com/v2/commerce/exchange/coins?quantity=200

Greetings,
Teranas

**Comment by lye** [comment]
Will have to wait until Monday to take a look at this -- likely something's gone amiss on one of the backend servers the API talks to.

**Comment by lye** [comment]
[Forum ref](https://forum-en.guildwars2.com/forum/community/api/API-errors-bugs/6051538).

**Comment by lye** [comment]
Deployed the fix.
