### ISSUE TITLE
/v2/account/ - Add Mastery Level

### ISSUE THREAD

**Issue by milneti** [arenanet/api-cdi#273]
in reference to PR #115 , mastery level is account wide and should be added accordingly.I am assuming this is easily obtainable in the back end (I hope :) ) In addition, it could be useful to add the mastery Icons (magumma , tyria, mastery page header) to the files dump to be accessed application side?

**Comment by lye** [comment]
Yeah, it's do-able. In addition to the raw mastery level, going to need to provide `/v2/masteries` which provides localized dumps of the mastery data (lines, names, costs, etc).
