### ISSUE TITLE
Invalid API keys getting generated?

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#284]
Today a user messaged me with an interesting problem. This is his API key:

```
62553175-579F-2341-9ECB-71AEA982C7A6F910E7AF-444A-B9AB-1B2DC7A53A8B
```

As you can see, it doesn't even fit the format of normal API keys (the last 4-number block is missing). The problem did persist, even when trying to generate multiple different API keys, with different sets of permissions.

**Comment by lye** [comment]
Discussed [on gitter](https://gitter.im/arenanet/api-cdi?at=5715325d2c9711166432feb8); need more information to debug.

**Comment by queicherius** [comment]
This was an issue on the user's end. Probably a bad browser extension.
