### ISSUE TITLE
Some ids return from v2/achievements/daily appear to be invalid

### ISSUE THREAD

**Issue by iLovePorkDumpling** [arenanet/api-cdi#288]
These ids, for example, are 2968, 1892, 1883, which I obtained from today (4/19/2016) v2/achievements/daily using url -> https://api.guildwars2.com/v2/achievements?ids=1975,1938,1963,2968,1892,1883

When called achievements api with these ids using this url -> https://api.guildwars2.com/v2/achievements?ids=2968,1892,1883

The returned results from Anet API is the following:
{"text":"all ids provided are invalid"}

**Comment by lye** [comment]
This is fixed; the achievements needed to be whitelisted.

I'll try to keep on top of whitelisting this week since there's a bunch of new dailies again.

**Comment by iLovePorkDumpling** [comment]
Thanks a lot Lye!
