### ISSUE TITLE
New types on /v2/items

### ISSUE THREAD

**Issue by Gapplay** [arenanet/api-cdi#290]
Hi, I've found these:
{
  "id": 7xxxx,
  "details": {
    "type": "Longbow",// Must be Long**B**ow
    "type": "Shortbow",// Must be Short**B**ow
    "type": "Spear",// Must be **Harpoon**
    }
}

**Comment by lye** [comment]
Thanks for the heads up; I'll try to find where the discrepancy was introduced.

**Comment by lye** [comment]
The original serializations have been [restored](https://api.guildwars2.com/v2/items/13632). Sorry about that :<
