### ISSUE TITLE
`recipes` missing from `/v2/characters/:id`

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#293]
It seems that `recipes` has disappeared from the output of the `/v2/characters/:id` endpoint. `/v2/characters/:id/recipes` is returning `{}`.

The API keys I tried  have all permissions. I've tried generating a new key just to be sure, but that didn't change anything.

**Comment by lye** [comment]
I changed it to require the `"inventory"` permission (instead of `"inventories"`).

Deploying the fix now, sorry about that ;__;

**Comment by lye** [comment]
Deployed and [verified working](https://api.guildwars2.com/v2/characters/Shieldclaws/recipes?access_token=1B410E2E-DECA-D248-9354-82724F218D753D7EAAC2-BBC8-4051-9AEB-FD3DEC6BD0FF). Sorry again about that mishap.
