### ISSUE TITLE
More achievement ids returned from Daily ap appear to be invalid/missing infomation

### ISSUE THREAD

**Issue by iLovePorkDumpling** [arenanet/api-cdi#295]
Ids: 1966, 2922
Repro using this url --> https://api.guildwars2.com/v2/achievements?ids=1966,2922
Return result: {"text":"all ids provided are invalid"}

Is there a way to figure out all new daily ids which have missing information and fix it all instead of incrementally?

**Comment by lye** [comment]
There probably is; I should look at that tomorrow. In the meanwhile I've whitelisted today and tomorrow's dailies.

**Comment by iLovePorkDumpling** [comment]
Thanks a lot Lye. Really appreciate the quick turn around. Impressive! :)

**Comment by lye** [comment]
Whelp, checked in a bit that automatically whitelists the daily achievements. Finally.

**Comment by iLovePorkDumpling** [comment]
Thanks a lot lye!
Today's achievement id has missing data again. It's #id 1924. Could you help add the data as well?

**Comment by hackedd** [comment]
And 2980 today.

**Comment by hackedd** [comment]
And both 1907 and 2980 today...

**Comment by lye** [comment]
Yeah, weekends are bad since I have to remember to VPN in and whitelist them. This should be a moot point in a couple of weeks (or whenever that auto-whitelisting bit goes out). Sorry :<

**Comment by lye** [comment]
Pretty sure this is all working now. There's still going to be some downtime when we do a new release -- there's support in to automatically whitelist achievements, but since we do some quick QA on live before the new patch is announced I'd rather have a manual step so that the API doesn't spill the beans too early.
