### ISSUE TITLE
Use Accept-Language header if lang parameter is omitted

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#30]
It would be nice if the APIs used the Accept-Language header when the lang parameter was omitted from requests. This would allow sites that use AJAX requests to localize more easily.

**Comment by tivac** [comment]
`Accept-Language` has lots of problems, but it's better than nothing. I'm :+1: on this.

**Comment by tivac** [comment]
This is in on dev, it'll go out at some point in the future when @lye does a deploy.

**Comment by StevenLiekens** [comment]
That was fast. I thought this was low priority? Not complaining, just wondering.

**Comment by tivac** [comment]
It was a tiny change and I had some spare time.

**Comment by StevenLiekens** [comment]
It's kind of a rough header to implement according to the spec. Do we get support for multiple values? Quality values?

**Comment by tivac** [comment]
It's not all that bad, really. We have an existing shared implementation in the core of our web application code, so all I did was replace the API specific `?lang=xx` parsing with the one in core.

It'll prefer `?lang=xx` values, but fallback to the `Accept-Language` header (including support for multiple values and quality levels). If none of those match it defaults to english.

**Comment by StevenLiekens** [comment]
Sweet! That's awesome.

**Comment by tivac** [comment]
This is deployed.
