### ISSUE TITLE
Wrong white space character at french fractal dailies

### ISSUE THREAD

**Issue by robertluedke** [arenanet/api-cdi#306]
When receiving the french version of daily tier fractal dailies there is a wrong white space character in the name of the achievement.

**Example:** https://api.guildwars2.com/v2/achievements/2966?lang=fr
**Result:**
{"id":2966,"icon":"https://render.guildwars2.com/file/620E0D3D2DD860700632BA7B3AC10C44CE55FD6C/1424206.png","name":"Niveau 4 quotidien de la fractale du boss de la Fusion","description":"","requirement":"Terminer la fractale du boss de la Fusion au niveau 76 ou supérieur.","type":"Default","flags":[],"bits":[{"type":"Text","text":"Niveau de la fractale : 99"},{"type":"Text","text":"Niveau de la fractale : 90"}],"tiers":[{"count":1,"points":0}],"rewards":[{"type":"Item","id":78572,"count":1}]}

**Problem:**
_"name":"Niveau 4 quotidien de la fractale du boss de la Fusion"_
The white space between 'Niveau' and '4' is an extended ascii character 194 and 160 instead of a simple blank sign.

**Comment by lye** [comment]
Thanks, I'll see if I can get this to our localization team.

**Comment by lye** [comment]
Okay, so the loc team got back to me last week and said the use of a non-breaking space was unintentional. I believe this is fixed on live:

```
fetch("https://api.guildwars2.com/v2/achievements/2966?lang=fr")
    .then((res) => res.json())
    .then((res) => console.log(res.name.charCodeAt(6)))

32
```
