### ISSUE TITLE
/v2/wvw/objectives -- EotM coords wrong.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#308]
[forum ref](https://forum-en.guildwars2.com/forum/community/api/API-errors-bugs/6142809).

Guessing one's assigned to the wrong sector.

**Comment by codemasher** [comment]
![Uploading wvw-region.png…](the c2/f3/r7 label and continent_rect is a little off...)

**Comment by lye** [comment]
Well, the objective coordinates are right at least. Still need to look into the continent rect issues.

**Comment by codemasher** [comment]
Here's a widget to quick test http://wiki.guildwars2.com/wiki/Widget:Map_floors/test#broken
```
{{#Widget:Map floors|continent_id=1|floor_id=1|region_id=11|zoom=2}}
```

**Comment by codemasher** [comment]
welp, seems like you need to mve a bit stuff now

![progress](https://cloud.githubusercontent.com/assets/592497/18368401/190cda18-7620-11e6-967c-7aac211e792b.png)

**Comment by lye** [comment]
Everything's looking correct currently; IIRC the continent rect issues were due to the tiles being out-of-sync with the content (the rect changed a couple of times to support alpine BLs). Going forward, regenerating tiles in a prompt manner (e.g., with every release) should prevent the latter problem from resurfacing.
