### ISSUE TITLE
/v2/account/ - Add a way to know account leads a guild

### ISSUE THREAD

**Issue by milneti** [arenanet/api-cdi#310]
Currently account endpoint returns the guilds that an account is a member of, but there is no way (that I know of?) to know whether the account has the ability to utilize the authenticated guild/:id/X endpoints.

Ideally it would make sense for the guilds array to return objects with the guild ID as well as the member status (leader or member), but this would be breaking at this point.

So, perhaps this is a quicker / not breaking solution? Just adding a key for leader that exists only if the account leads a guild.
"guild_leader" : "DA9137CD-3A86-E411-B57A-00224D566B58"

This would prevent apps from having to poll a guild/:id/X endpoint for each guild ID for an account to see if any data is returned.

Thanks!

**Comment by lye** [comment]
`guild_leader` should probably be an array of GUIDs, but otherwise that makes sense to me.

**Comment by Aidansavage** [comment]
would it make more sense to convert the guild return from

guilds: [
"6DA03D40-EDAD-E311-BB46-80C16E7C6D65",
"7F6DCB0B-AECB-45B5-A6E2-2CCE1608FD58",
"59E15C7E-10F9-E411-A5A9-AC162DAE5A05"
],

to:

guilds: [
["6DA03D40-EDAD-E311-BB46-80C16E7C6D65", "/rank"],
"7F6DCB0B-AECB-45B5-A6E2-2CCE1608FD58", "/rank"],
"59E15C7E-10F9-E411-A5A9-AC162DAE5A05", "/rank"]
],

or would this not work as is?

**Comment by lye** [comment]
It would need to be a different field to preserve backwards-compatibility, e.g

```
guild_ranks: [
    [ "6DA03D40-EDAD-E311-BB46-80C16E7C6D65",  "Leader" ],
    [ "7F6DCB0B-AECB-45B5-A6E2-2CCE1608FD58", "Officer" ],
    [ "59E15C7E-10F9-E411-A5A9-AC162DAE5A05", "Member" ]
]
```

Putting the rank names in there is kind of sub-optimal though since they're just arbitrary strings -- a guild can be set up such that the leader name is anything. Feel like it might as well be a list of guild ids, e.g.

```
"guild_leader" : [
    "6DA03D40-EDAD-E311-BB46-80C16E7C6D65"
]
```

**Comment by FreezyExp** [comment]
5 guilds to test in a worst case scenario, just catch the error to list it as: not a leader of

But yes "guild_leader" : [ "Guild ID1", "Guild ID2" ] would be a welcome addition

**Comment by queicherius** [comment]
This would be super helpful, right now the only way to get all guilds of an account is to send requests to all it's guilds and ignore any responses with `400` status errors, which is kind of iffy.

**Comment by lye** [comment]
`guild_leader` is in.
