### ISSUE TITLE
/v2/characters entries should have unique, immutable ids

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#32]
Because name change contracts, blergh.

**Comment by lye** [comment]
(this is more difficult than it sounds, I swear)

**Comment by darthmaim** [comment]
Don't waste too much time on this and instead continue to release all those other awesome features. Now that we have `created` for each character we can use that to track renames, `created` should be mostly unique for each character per account (at least in combination with profession/race/gender).

I guess name changes aren't happening that often anyway, so we should be good for now.
