### ISSUE TITLE
/v2/traits -- tier field is totally broken

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#325]
[These two minor traits are reversed](https://api.guildwars2.com/v2/traits?ids=2004,264&lang=en). Apparently the "tier" field is absolutely meaningless and isn't used by the client; it needs to be inferred from the position within an array instead.

[gitter ref](https://gitter.im/arenanet/api-cdi?at=5745ede5548104867b6814ba).

**Comment by BryghtShadow** [comment]
Relevant: https://forum-en.guildwars2.com/forum/support/bugs/Arcane-minor-trait-in-wrong-slot/

* In the Training tab: Arcane Fury, Elemental Attunement, Elemental Enchantment.
* In the list of Traits (left of Build tab): Arcane Fury, Elemental Enchantment, Elemental Attunement.
* In the Specializations (right of Build tab): Arcane Fury, Elemental Attunement, Elemental Enchantment.

(What is the correct tier order: the Training+Specialization, or the list of traits?)

**Comment by lye** [comment]
It looks like they're all in the right order now: Fury, Attunement, Enchantment.
