### ISSUE TITLE
/v2/floors/pois - add GUID for heropoints

### ISSUE THREAD

**Issue by codemasher** [arenanet/api-cdi#329]
as per https://gitter.im/arenanet/api-cdi?at=575aec4637340f6b2fe263aa
(starts at https://gitter.im/arenanet/api-cdi?at=575aeacac046fa5b2fd53ed8)

**Comment by lye** [comment]
I need to look up how these are referenced by the character blob. There might be a unique integer id which has nothing to do with the hero point that I can use (rather than the GUID).

**Comment by codemasher** [comment]
HARDCODE ALL THE THINGS?

**Comment by lye** [comment]
These went in as strings rather than guids -- this saved some effort for `/v2/characters/heropoints` which needs to dump out correlating ids (and doesn't have the guids). But the `skill_challenges` array now has `id`s, hooray.
