### ISSUE TITLE
v2/continents/ doesn't always state the floor id

### ISSUE THREAD

**Issue by ChieftainAlex** [arenanet/api-cdi#348]
**Issue:**
The floor is not always given for the "points_of_interest" in the continents endpoint. Possibly affects other key value pairs, haven't checked.

**Example affected by issue:**
https://api.guildwars2.com/v2/continents/1/floors/2/regions/10/maps/1165

**Reference:**
https://gitter.im/arenanet/api-cdi?at=5797c108ad8f331f4e4a6572

**Comment by lye** [comment]
I don't remember fixing this but I marked it as `needs deploy` and also it seems to be fixed >__>
