### ISSUE TITLE
Daily Fractal API does not return the new Fractal 'Chaos' in the ID

### ISSUE THREAD

**Issue by iLovePorkDumpling** [arenanet/api-cdi#349]
Today's (7/28/2016) Daily Fractal has the new Fractal 'Chaos Isles' as well. However, calling the api --> https://api.guildwars2.com/v2/achievements/categories/88 does not return the daily fractal id which is for Chaos Isles, whereas other daily fractal ids are return correctly.

Once the ID is return from that api, please make sure the achievement details for that id is also return with the achievement detail api as well.

Thanks a lot!

**Comment by lye** [comment]
`/v2/achievements/categories/:id` filters the list based on what's in `/v2/achievements`. Just went through the whitelist queue and blessed the new dailies, so they should start appearing in both endpoints soon. Will close this once I verify.

Sorry about the mess :(
