### ISSUE TITLE
Collection items from the new Bloodstone Harvest achievement do not exist

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#350]
In [the Bloodstone Harvest achievement](https://api.guildwars2.com/v2/achievements/3090) there are collection items that do not exist in `/v2/items`. Collection items that do not show up: 79352, 79333, 79331, 79347, 79349, 79350, 79348, 79330, 79323, 79308, 79324, 79355, 79314, 79359, 79332.

Ref:
- https://gitter.im/arenanet/api-cdi?at=57aa37ba46610f17394cb026
- https://gitter.im/arenanet/api-cdi?at=57ac6b18ff82b9fc7e750dc8

**Comment by lye** [comment]
Ick. Really need to make those auto-whitelist, so many things to do.

In the meanwhile I've manually whitelisted the ones that weren't already whitelisted. Sorry about the delay :<
