### ISSUE TITLE
Duplicate skin entry for the Bloodstone Visage Skin

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#351]
The [Bloodstone Visage Skin](https://api.guildwars2.com/v2/items/79311) has a duplicate skin 6893 listed. I don't know if this is the only one with a duplicate skin entry.

I assume that it shouldn't contain duplicates, since it's quite useless, unless it has a function that I don't know about.

**Comment by lye** [comment]
I added a skin id dedupe to the item normalization bits. Will go out whenever the next deploy happens.
