### ISSUE TITLE
/v2/backstory/answers: missing mesmer choices

### ISSUE THREAD

**Issue by BryghtShadow** [arenanet/api-cdi#352]
I cannot find the 3 mesmer mask choices in https://api.guildwars2.com/v2/backstory/answers?ids=all
Sample data:
* Kaori Emora: `{"backstory":[53,105,108,157,189]}`
* Illusionary Riqua: `{"backstory":[53,69,72,74,188]}`

**Comment by lye** [comment]
Umm. Hmm.

That's a real interesting bug you've found there: the answers have hand-entered ids (which are persisted to the character blobs, so are effectively immutable), but the mesmer answers and revenant answers have the same ids.

I'll uhh, see what I can do to normalize that on the frontend.
