### ISSUE TITLE
/v2/colors returns wrong item id

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#353]
[forum ref](https://forum-en.guildwars2.com/forum/community/api/API-2-colors-returns-wrong-item-id)

> Hello, I’m working with API:2/colors and when I want to get the item that unlocks a color the system returns an error about item not found.
> I have tested the https://api.guildwars2.com/v2/colors/10 that is on wiki as example and the item id is different: on wiki is 20370 (the right one) while from api is 65149 (absolutly wrong).
Seems that almost all the colors now have a wrong item id!

The item 65149 doesn't exist and 20370 correctly contains 
```js
"details": {
  "type": "Unlock",
  "unlock_type": "Dye",
  "color_id": 10
}
```

/v1/colors.json returns the correct item.

**Comment by lye** [comment]
Color unlock items are now filtered to include only what's in `/v2/items` (and not test/GM-only items >_>).
