### ISSUE TITLE
/v2 should explain authentication

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#370]
https://api.guildwars2.com/v2 explains how to use bulk expansion and localization, but doesn't mention authentication.

> Authentication:
> 
> Authenticated endpoints require an API key. You can pass them via the `Authentication` header (`Authentication: Bearer <API key>`). If you can't create custom headers (i.e. because CORS), the API key can be passed via query parameter as `access_token=<API key>`.
> 
> Users can create API keys on their account page (https://account.arena.net/applications).

**Comment by lye** [comment]
Also the list of endpoints should include a flag (similar to the language flag) indicating whether or not they're authenticated.

**Comment by lye** [comment]
Blammo.

**Comment by hackedd** [comment]
It would be nice though if this was also added to the [JSON version](https://api.guildwars2.com/v2.json), as suggested in #368.

**Comment by lye** [comment]
Garfabablsj.

**Comment by lye** [comment]
For real this time.
