### ISSUE TITLE
/v2/account/bank -- missing items

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#386]
It only lists some of the bank items (e.g. 240 slots = 8 out of 12 tabs for me). Seems to be for all users (some report 8 out of 12, someone reported 3 out of 4). My tabs all have items in them. Key if needed `BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041` (should return array with 360, returns array with 240)

(Copy/paste from [gitter](https://gitter.im/arenanet/api-cdi?at=580628fab17b667961d10cd2))

**Comment by kepi** [comment]
I have same problem, only 8 from 12 bank tabs returned.

**Comment by lye** [comment]
Fix is live -- sorry about the delay! :<
