### ISSUE TITLE
Trait icons transparency inconsistent

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#387]
I've recently found that certain trait icons have a transparent border, whereas others don't. Instead, they are rendered with a black border.

Example:
- [Trait 706](https://api.guildwars2.com/v2/traits/706) - Critical Infusion - Mesmer, Dueling Adept Minor: [Icon without transparency](https://render.guildwars2.com/file/ADBABE00177C2A79CA7725F2217D2165CB086239/1012507.png)
- [Trait 2030](https://api.guildwars2.com/v2/traits/2030) - Time Splitter - Mesmer, Chronomancer Adept Minor: [Icon with transparency](https://render.guildwars2.com/file/5A9347250FEF7B3431ECE3F6689EDCE20FB96CB6/1012483.png)

It might very well be that this is how the icons are stored internally. Which is weird to have inconsistency. However, there's also 2 images in the .dat file (1002159 for major, 1002160 for minor) that are the alpha masks for these trait icons.

Is it possible to have these icons with the alpha masks applied on render? Or is it impossible due to how they are saved in the .dat file this way?

**Comment by lye** [comment]
Not really possible to apply the alpha mask on render -- the render component doesn't have any clue what it's rendering. I did add the alpha mask to `/v2/files` -- the other alternative is to clip the images on the frontend (e.g., with [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)).

**Comment by Archomeda** [comment]
Yeah, the issue with clip-path is that not all browsers seem to support it just yet. Anyway, having the mask in `/v2/files` is great as well, thanks!

**Comment by lye** [comment]
Not really sure what happened here; I guess I forgot to submit or something? wtf.

**Comment by lye** [comment]
Okay, [these are in](https://api.guildwars2.com/v2/files?ids=ui_minor_trait_mask,ui_major_trait_mask).
