### ISSUE TITLE
Proposal add exploration details to characters endpoint

### ISSUE THREAD

**Issue by derRAV3N** [arenanet/api-cdi#39]
Just return the percentage of world completion and each number of completed hearts/wp's/vistas.

If there's time to go deeper maybe add an argument to return percentage and completed things of one map only.

**Comment by jantman** [comment]
I'd be very interested in this on a per-map/tile level. I'm relatively new to GW2 (only have been playing for a few months) and just started looking into the API tonight. I've just been trying to come up with (for my character) as list of zones by map completion %...

**Comment by Aonwy** [comment]
Closing for organizational reasons. If this is something you still want, please create a new ticket.
