### ISSUE TITLE
/v2/items -- Missing ids for halloween guild decorations

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#390]
Some of the new Halloween guild decorations have their recipes in the API, but are missing their items:

- Hanging Tree (`[&AgEoNwEA]`, recipe `11872`, points to item `79656`)
- Demon Statue (`[&AgEZNwEA]`, recipe `11873`, points to item `79641`)
- Mad Moon (`[&AgEdNwEA]`, recipe `11874`, points to item `79645`)
- Mausoleum (`[&AgFINwEA]`, recipe `11875`, points to item `79688`)

```js
# https://api.guildwars2.com/v2/items?ids=79656,79641,79645,79688
{"text": "all ids provided are invalid"}
```

In contrast, the new [Eternal Flame](https://api.guildwars2.com/v2/items/79642) guild decoration exists.

**Comment by tivac** [comment]
Hmm, afaik the whitelisting queue is empty but I'll take a look when I'm in the office tomorrow.

**Comment by lye** [comment]
Whitelisted those.

Gonna poke at the whitelist bits so that recipes with guild upgrade outputs stuff the corresponding guild upgrade items into the queue.

**Comment by lye** [comment]
I'm totally baffled as to why those aren't appearing in the whitelist. From what I can tell, whitelisting a recipe should automatically whitelist both the `output_item_id` and all ingredients. Going to chalk this up to something really weird (maybe a temporary failure? it has to look up the recipe details and the component that handles content sometimes times out).
