### ISSUE TITLE
/v2/continents/.../map mastery point and adventure coords not projected.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#393]
[gitter ref](https://gitter.im/arenanet/api-cdi?at=583581ed9a5479d0485006f2).

I am dumb and didn't transform the output coordinates into the continent space.

**Comment by lye** [comment]
Backend fix for this should have gone out awhile back.

**Comment by ChieftainAlex** [comment]
No idea what you did to the adventure part of this, but adventures are blank for all maps.

**Comment by ChieftainAlex** [comment]
| In the API? | Name | Zone | Location | Notes                                                                              |
| - | - | - | - | - |
| Yes | Tendril Torchers | Verdant Brink | Dry Step Mesas | Day only                                                        |
| Yes | Salvage Pit | Verdant Brink | Shrouded Ruins | Day only                                                             |
| Yes | Bugs in the Branches | Verdant Brink | Jaka Itzel | Day only                                                        |
| Yes | Shooting Gallery | Verdant Brink | Hidden Copse | Day only                                                          |
| Yes | Flying Circus | Verdant Brink | Blighted Depths | Day only                                                          |
| No | The Floor Is Lava? | Auric Basin | Tarnished Treetop | Not during assault.                                           |
| No | On Wings of Gold | Auric Basin | Tarir, the Forgotten City | Not during assault.                                     |
| No | Sanctum Scramble | Auric Basin | Tarir, the Forgotten City | Not during assault.                                     |
| No | Fallen Masks | Auric Basin | Tarir, the Forgotten City | Not during assault.                                         |
| No | A Fungus Among Us | Auric Basin | Griffonfall | Not during assault.                                                  |
| No | The Ley-Line Run | Tangled Depths | Ogre Lane | Not during assault.                                                  |
| Yes | Drone Race | Tangled Depths | SCAR Bivouac | Not during assault.                                                    |
| Yes | Beetle Feast | Tangled Depths | Teku Nuhoch | Not during assault.                                                   |
| No | Haywire Punch-o-Matic Battle | Tangled Depths (instance) | Haywire Punch-o-Matic Battle (#1115) | Not during assault.|
| No | Scrap Rifle Field Test | Tangled Depths (instance) | Scrap Rifle Field Test (#1110) | Not during assault.            |
