### ISSUE TITLE
/v2/account -- Include the account age

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#405]
It would be nice if the account endpoint also included the account age and playtime (basically the output when you type `/age` in the in-game chat).

Currently, our only way to measure account playtime is by adding up the playtime of all characters, which is an issue when characters get deleted (this is especially apparent with PVP players that recreate their characters).

**Comment by lye** [comment]
When a character is deleted, does the result of `/age` change? I'm presuming it doesn't.

**Comment by lye** [comment]
![untitled](https://cloud.githubusercontent.com/assets/921652/21062662/af4069fe-be06-11e6-8630-01c1c3dfdc6e.png)

My brain hurts. I think I found where this is stored though, so should be good to go.

**Comment by Coffee4cr** [comment]
That doesn't add up

**Comment by queicherius** [comment]
> When a character is deleted, does the result of /age change? I'm presuming it doesn't.

No, the playtime stays the way it is (and that is the value that we can't get atm, since we can only get the characters)
