### ISSUE TITLE
Infusion upgrade changes

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#408]
A while ago the infusions saw some changes. Previously we had *offensive infusions*, *defensive infusions* and *utility infusions*. Nowadays we have only *infusions* and *enrichments*.

Looking at the API, I don't think it's been updated yet.
- [Amulet](https://api.guildwars2.com/v2/items/39273): should have the enrichment slot.
- [Ring](https://api.guildwars2.com/v2/items/75669): should have 1/2/3 infusion slots (depends on non-infused, infused/attuned, infused and attuned)
- [Armor](https://api.guildwars2.com/v2/items/48072): should have an infusion slot
- [Weapon](https://api.guildwars2.com/v2/items/46762): should have 1/2 infusion slots

`.details.infusion_slots[].flags` is always empty now. I think that having the `Infusion` and `Enrichment` flags will fix this issue.

- [Enrichment](https://api.guildwars2.com/v2/items/39333)
- [Infusion](https://api.guildwars2.com/v2/items/77310)

`.details.infusion_upgrade_flags` is always empty now. Same as above, I think that having the `Infusion` and `Enrichment` flags will fix this issue here too.

**Comment by lye** [comment]
Added those new enumeration values -- should start appearing in both places in a month or so.
