### ISSUE TITLE
/v2/wvw/matches endpoint becoming cluttered

### ISSUE THREAD

**Issue by mcd1992** [arenanet/api-cdi#412]
The matches endpoint contains a decent amount of data as is. And will contain more data in the future. See https://github.com/arenanet/api-cdi/pull/397 and https://github.com/arenanet/api-cdi/pull/381

We definitely need to keep the current state of the endpoint as is for backwards compatibility but if possible it might help with the API load to split some of the matches.json endpoint into a few new endpoints in /v2/wvw/

Some scripts have to query the matches.json endpoint multiple times a minute for up to date score/kdr tracking. And in doing so a lot of objective/map data is sent and discarded by the client. I think 4 new endpoints would help with this problem. An endpoint for just scores, global and per map. Endpoint for worlds partaking in this skirmish. Endpoint for kills/deaths global/per-map/per-team. And a endpoint for per map info; could re-use the matches endpoint and just add something like '/v2/wvw/matches/1-1?map=98' or 'matches?world=1001&map=98' ect.

### match-stats
```/v2/wvw/match-stats?id=1-1```
```/v2/wvw/match-stats/1-1```
```/v2/wvw/match-stats?world=1001```

Which will return data similarly to matches.json. Except missing the objectives array and some of the 'static' data that wont change during the skirmish/week. This would also hopefully allow the kills/deaths to update more quickly (instead of at the end of each map tick) like the scores currently do.

### match-scores
```/v2/wvw/match-scores?id=1-1```
```/v2/wvw/match-scores/1-1```
```/v2/wvw/match-scores?id=1-1&map=98```
```/v2/wvw/match-scores?world=1001&map=98```

Which will return score (not kills/deaths/yaks/ect) data pertaining to either all worlds in the match id or just the specified world. Allow 'map=' to filter down to just a specific map in the skirmish.

### match-kd
```/v2/wvw/match-kd?id=1-1```
```/v2/wvw/match-kd/1-1```
```/v2/wvw/match-kd/1-1?map=98```
```/v2/wvw/match-kd?world=1001&map=98```

Which will return kills and deaths (not score/yaks/ect) data pertaining to either all worlds in the match id or just the specified world. Allow 'map=' to filter down to just a specific map in the skirmish.

##
I figure some of this might not be implementable with the current API setup but I'd like to hear what can be implemented. Especially hoping for a endpoint with more quickly updated kills/deaths.

**Comment by lye** [comment]
> I figure some of this might not be implementable with the current API setup but I'd like to hear what can be implemented.

Looks all doable as-is. Making changes to the API frontend to change the output format a bit is super straightforward.

> Especially hoping for a endpoint with more quickly updated kills/deaths.

This bit isn't feasible without significant changes -- the way k/d tracking works is by reading the logs emitted by the map instance servers (the API servers can't talk directly to the map instance servers). Our log system is best-effort, so latency on it can vary anywhere between a few seconds to fifteen minutes. There's probably a better way to implement k/d tracking, but it probably involves pulling in some other systems which I'm unfamiliar with.

Anyway making the k/d update faster is definitely a separate issue.

**Comment by lye** [comment]
@mcd1992 when you have a chance, would you look over #416 and let me know what you think?
