### ISSUE TITLE
/v2/guild/:id/log: upgrade events have item ids, not upgrade ids.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#425]
Oops.

 * [forum ref](https://forum-en.guildwars2.com/forum/community/api/guild-log-upgrades)
 * [forum ref](https://forum-en.guildwars2.com/forum/community/api/Unusual-ID)

**Comment by lye** [comment]
Guh, this is going to take a full release cycle to fix. The backend component which reads the dat file isn't currently outputting enough data to get the upgrade id from the item id.

**Comment by lye** [comment]
The frontend support for this is in -- offending log entries will now have an `item_id` field. Once the backend support lands (in a month? I don't know what the release schedule looks like) the corresponding `upgrade_id` field should start appearing.

**Comment by Mjesko** [comment]
Not sure if it's a bug or just related to the upcoming backend changes but currently the "treasury" events seem to lack the user field and the amount is always 1:
  {
    "type": "treasury",
    "item_id": 19721,
    "count": 1,
    "id": 157180,
    "time": "2017-01-13T08:16:56.000Z"
  }
I'd provide a gild ID if it's a bug and not related to the backend.

**Comment by lye** [comment]
I definitely broke something, the code doesn't even match the comments

```
        // poolType indicates the reason for the escrow:
        //   2 = ESCROW_POOL_TYPE_UPGRADE_COMMON, e.g., treasury deposit
        //       poolId is unused.

        if(poolType === 2 && poolId === 0 && resourceType === 1) {
            // Normal treasury deposit of an item.
```

Should be able to repro locally since it looks so broken, but a guild id never hurts.

**Comment by Mjesko** [comment]
F22D63A0-60CB-E411-A2AD-AC162DC0A8ED
The guild ID matches the guild from which i've taken the log entry above, so the ID of the log entry should be one of the broken ones.

**Comment by lye** [comment]
Just deployed a fix on live, thanks for the heads up <3

**Comment by Mjesko** [comment]
Thanks for the fix and your time! :)
