### ISSUE TITLE
Request: /v2/models - character model endpoint

### ISSUE THREAD

**Issue by Valento92** [arenanet/api-cdi#429]
Hey, a rather big request here that's being talked a lot. Although I think it may never see the daylight I'd like to request an endpoint to retrieve character models. This is a non-authenticated scheme, responsible for loading the model itself. The authenticated counterpart could return aesthetics choices and slider values, as discussed [here](https://forum-en.guildwars2.com/forum/community/api/end-point-for-character-proportions/first#post6314640).

Some ideas around it:
-  Akin to tile service **address** could be `https://models.guildwars2.com/{race}/{gender}` &ndash; first access to the backend specifying desired race and gender.
- Retrieved model would be standard position like that_shaman does, no fancy positioning or variable animation frame state as this is not quite necessary. If instead of standard position we could have in-game first animation frame (more relaxed look) it would be much better.
- Model could be served as a common web-friendly format like COLLADA or plain JSON, whichever hurts less. :)

Parameters could be everything the backend renderer would use, and would accept numbers respective to the choice. These same numbers could come from an appearance endpoint, under the authenticated characters endpoint:
- **height**: character height;
- **skin-color**: skin color;
- **physique**: the character physique (bulky, thin, fat, etc);
- **pattern/pattern-color**: asura's skin markings, norn's tattoos, etc.;
- **hairstyle/hair-color/hair-accessory-color**: self-explainable;
- **face/facial-hair**: facial-hair is only available to humans;
- **ears/horns**: ears are replaced by horns for charr.

For the other complex **eyes**, **nose**, **mouth**, **chin-jaw**, **ears-choices**, **muzzle** (charr) and **horns** (charr) it could be a list of comma-separated values (either length, width, etc), retrieved from appearance endpoint (not sure if updated but [this page](https://wiki.guildwars2.com/wiki/Physical_appearance) lists the appearance variations). Colors couldn't be hex values because the game has a predefined system, so either the in-game name or a number value respective to a certain color.

Massive example:
- `https://models.guildwars2.com/asura/female?height=1.65&skin-color=54&physique=5&pattern=2&pattern-color=34&hairstyle=1&hair-color=21&face=12&ears=2&eyes=1,6,4,5,2,9,12&nose=3,7,1&mouth=1.6,7.2,5,1&chin-jaw=1.7,4,1,1,6&ears-choices=1,3.5,2,1`

These are all made up numbers, but would describe specific choices for a certain character model to be used by the renderer.

Finally, this could be an authenticated endpoint but the structure would replace all these options fed into the url by account API and a specific character name. This way the backend would resolve the whole thing by itself. Consider that this allows users to create appearances outside the game, providing a way to preview character looks before purchasing kits.

Cheers.

**Comment by Valento92** [comment]
One more thought that sparked: you could avoid composing and providing the model file, and instead take a snapshot of the character model's current state. It is not optimal as this request aims viewing the character model like WoW Armory does, but it's something.

**Comment by lye** [comment]
Interestingly, the model loading bits are encumbered by the same refactoring blocker as #430 -- the model loading bits pull in the audio bits which pull in some other bits etc which hit static assertions because they're not designed to be run on a server which has no window context. Internally, we use a proprietary model format, so using the existing model loader is pretty important. Would probably dump it to OBJ since I'm familiar with it -- COLLADA supports shader/effect references but I'm not exactly sure how we'd expose effects (not to mention textures and the rest of the data attached to models).

Do any other games have an officially-supported API for retrieving unrendered model data?

**Comment by Valento92** [comment]
Ah, everything you said is understandable. Dumping to OBJ seems to me it would end up being bigger than COLLADA, but it should do. WoW had a 3D character viewer, but the armory belonged to the company so no legal issues with that. This same armory got disabled at some point though. I am not sure how ANet would handle exposing their models (although that_shaman already data-mines them, even if it is against rules). Capturing a snapshot would be safer if you don't really feel comfortable with that, and I honestly understand ya.

**Comment by lye** [comment]
I talked to some people; the current decision is that we're not willing to provide the raw model data. Even Exposing them via the API would put them under the API content license which isn't something we want to do.

**Comment by Valento92** [comment]
Alright, thanks for looking into it. Appreciate the response. :)
