### ISSUE TITLE
Add weekly raid resetting progression counters

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#434]
I have no clue which endpoint this can be put in. Maybe you can poke at the responsible people for implementing this as weekly achievements without rewards or anything. Then you might be able to implement this alongside the daily achievement progression.

In any case:

**Forsaken Thicket: Spirit Vale**
- Vale Guardian
- Gorseval
- Sabetha

**Forsaken Thicket: Salvation Pass**
- Slothasor
- Bandit Trio
- Matthias

**Forsaken Thicket: Stronghold of the Faithful**
- Escort
- Keep Construct
- Xera

**???: Wing 2-1** (listed it for when it gets released, don't know how long implementing this feature might take)
- Something boss 1
- Something something boss 2
- Something something more boss 3
- Something something last boss 4

Note: The server does remember from where you left off when opening a new instance, but this is not reliable since you will still open in Vale Guardian if you cleared Gorseval without doing Vale Guardian first (I think).

**Comment by Darqam** [comment]
Similarly, if this could be done, an extra piece of information could be daily dungeon path completion.
