### ISSUE TITLE
Item ID "70719" not found in `/v2/items`, but is found in `/v2/characters/<name>`

### ISSUE THREAD

**Issue by blakcap** [arenanet/api-cdi#439]
Here's the snippet that specifies this item ID:
```json
{
          "id": 70719,
          "count": 1,
          "upgrades": [
            72912
          ],
          "binding": "Character",
          "bound_to": "<name>",
          "stats": {
            "id": 153,
            "attributes": {
              "Vitality": 45,
              "Healing": 32,
              "ConditionDamage": 32
            }
          }
        },
```

I'm getting an invalid item id response.

~97ish% sure this item is my pair of medium Shaman's boots (60% sure it's the Bladed boots), since all the other Shaman equipment I have adjacent in my inventory are fetching correctly, but I don't see the boots in my app. Maybe something accidentally didn't get whitelisted?

It's honestly kinda funny that this hasn't been brought up already...guess Shaman's isn't too popular ._.

**Comment by lye** [comment]
I've whitelisted the item in the meanwhile; I've got a patch that automatically whitelists all of the items returned from inventory endpoints but there have historically been issues with it (it tears down servers) so I'm waiting for a good day to give it another shot.

**Comment by lye** [comment]
So that config's been on for awhile now and nothing's caught fire.

Whenever an unwhitelisted item is returned as part of an inventory it should be automatically whitelisted.
