### ISSUE TITLE
API key "copy" button seems broken.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#44]
It seems to be copying the entire page, not just the key.

**Comment by darthmaim** [comment]
Works for me?

**Comment by lye** [comment]
Maybe my browser/brain are broken.

**Comment by digiwth** [comment]
Requires Flash to be installed/enabled.

**Comment by codemasher** [comment]
I'd like to add a quote of a post i made on the forums:

>I’d also put the API key into an input-element instead of just leaving it as text node – just to make it more convenient for those who have flash disabled:

>```html
<input type="text" readonly="true" value="API_KEY_YO" onclick="this.select();" />
>```

**Comment by lye** [comment]
> Working for me, are you sure Flash is installed/enabled?

UHHH...

Okay, so those buttons really shouldn't be there if flash isn't enabled.

**Comment by lye** [comment]
Should be working now.
