### ISSUE TITLE
/v2/account/achievements -- Show the completed timestamps

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#440]
It would be neat so see when an account completed a specific achievement. Would also be interesting when an account repeated an achievement. Not sure if this is even possible, but I thought it wouldn't hurt to ask. 😄

**Comment by lye** [comment]
Unfortunately, we don't track achievement (or any progress) change times -- at least, not in a realtime-accessible way. The closest I can get is the "recently completed" achievements list which is just a static array in the account data that's updated whenever you progress an achievement.

**Comment by queicherius** [comment]
I guessed as much. The recently completed info is not that useful imo, that'd be another issue for someone to open. Thanks for the answer! 👍
