### ISSUE TITLE
/v2/achievements/daily -- add in fractal dailies too.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#441]
[forum ref](https://forum-en.guildwars2.com/forum/community/api/Move-Daily-Fractals-to-v2-achievements-daily).

Basically just hardcode the fractal category in there as well, for consistency reasons.

**Comment by darthmaim** [comment]
You created a PR for this last year: #338

**Comment by queicherius** [comment]
With #443 together, this would be perfect. 👍

**Comment by lye** [comment]
Oops, the issue didn't have a fixes note. This is fixed.
