### ISSUE TITLE
Extension of the API Key Permissions

### ISSUE THREAD

**Issue by Plitzz** [arenanet/api-cdi#45]
It would be helpful if you could its API Keys not only renaming, but also provided with additional rights.
The description also reads:

Editing API key

Enter a name, description, and permissions for this key. The fields for the name and description are for your personal use. Permissions determine which functions are made possible by using this key. Once the key has been created, you can not change the permissions.

**Comment by Eearslya** [comment]
If I'm not mistaken, we were already told this was technically impossible due to something in the backend servers.

**Comment by darthmaim** [comment]
Yep. [Source](https://forum-en.guildwars2.com/forum/community/api/HEADS-UP-OAuth2-being-replaced-next-week/page/2#post5077547):
> The current implementation for API keys internally use OAuth2 refresh tokens — the difference is that the account site is the OAuth2 client. Since the OAuth2 backend prohibits an OAuth2 token from adding new scopes, it’s just something we have to live with for the time being (though technically, we can add the ability to remove scopes, but that seems silly).

**Comment by lye** [comment]
I've definitely been feeling the pain on this issue; it's just not something we can fix in the near-term though :<
