### ISSUE TITLE
/v2/account/raids does not reset properly

### ISSUE THREAD

**Issue by gruntzy** [arenanet/api-cdi#458]
(already mentionned on [gitter](https://gitter.im/arenanet/api-cdi?at=58bd7096f1a33b627588496b))
**/v2/account/raids** still outputs the boss I've killed last week. I haven't killed anythig this week.
However, it seems that the output is correct for people who have killed a boss this week already.

Is the reset happening only after 1st kill, and is it an intended behavior ?

**Comment by Darqam** [comment]
Lye answered in Gitter: March 6, 2017 11:50 AM](https://gitter.im/arenanet/api-cdi?at=58bda16c7ceae5376a7c5966)

It isn't a kill requirement but a time elapsed since login instead.

**Comment by lye** [comment]
If you're still getting stale data 10 minutes after logging in, let me know and I can root around in the map instance code to see what's going on. That's the easy explanation I can think of, though.
