### ISSUE TITLE
/v2/commerce bug

### ISSUE THREAD

**Issue by jligeza** [arenanet/api-cdi#47]
This item:
https://api.guildwars2.com/v2/items/29978
Is supposed to be available on BLTC:
https://api.guildwars2.com/v2/commerce/prices
(actually, it doesn’t because it’s “SoulbindOnAcquire”)
But it returns something like this:
https://api.guildwars2.com/v2/commerce/prices/29978
And also this for listings:
https://api.guildwars2.com/v2/commerce/listings/29978

**Comment by lye** [comment]
This should be fixed as of last week.
