### ISSUE TITLE
'The Real Raiders of Tyria' max bits bug

### ISSUE THREAD

**Issue by MaxLepeh** [arenanet/api-cdi#473]
There is a bug in max number of bits in 'The Real Raiders of Tyria' achievement. It's done on my account in-game, but API says its not.

Request:
`https://api.guildwars2.com/v2/account/achievements?access_token=TOKEN&ids=3392`

Response:
`[
  {
    "id": 3392,
    "bits": [
      0,
      1,
      2,
      3
    ],
    "current": 4,
    "max": 8,
    "done": false
  }
]`

**Comment by lye** [comment]
Pretty sure the fix for this is live.
