### ISSUE TITLE
Super Adventure Box dailies missing from API

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#477]
It looks like the SAB daily achievement category is not whitelisted in the API, but the individual achievements are available ([Color Guard](https://api.guildwars2.com/v2/achievements/2856) for example).

**Comment by lye** [comment]
The fix for this is in, but won't make it through the release process in time for this year's SAB, unfortunately.

**Comment by lye** [comment]
[Looks like they're in](https://api.guildwars2.com/v2/achievements/categories/162).
