### ISSUE TITLE
Expose SAB unlocks for characters

### ISSUE THREAD

**Issue by Archomeda** [arenanet/api-cdi#480]
This would be a nice to have feature for people that have run SAB with multiple characters, but don't remember what they've unlocked per character. Sadly it's probably too late for 2017's release, but hopefully it will be on time for 2018.

The following unlocks are available (taken from the [wiki](https://wiki.guildwars2.com/wiki/List_of_Super_Adventure_Box_upgrades_and_skills)):

Skills | Notes
---- | ----
Pointy Stick (skill 1) | Unlocked by default or start
Chain Sticks (skill 1) | Replaces Pointy Stick
Slingshot (skill 2) |
Mini Bomb (skill 3) |
Whip (skill 4) |
Candle (skill 5) |
Torch (skill 5) | Replaces Candle
Health Potion (skill 6) | Unlocked by default or start / A quantity number
Medium Health Bottle (skill 6) | Replaces Health Potion / A quantity number?
Wooden Whistle (skill 7) |
Digger (skill 8) |
Nice Scoop (skill 8) | Replaces Digger
Glove of Whisdom (skill 9) |
Moto's Breath (skill 10) |
Moto's Finger (skill 10) | Replaces Moto's Breath

Upgrades | Notes
---- | ----
Bauble Purse | 250 -> 500 bauble storage
Bauble Tote Bag | 500 -> 750 bauble storage
Health Vessel 1 | World 1
Health Vessel 2 | World 2

Songs | Notes
---- | ----
Secret Song | 1-2-3-1-2-3
Gatekeeper Lullaby | 3-3-2-3-3-1
Shatter Serenade | 1-3-3-1-3-3

I'm not sure about a possible format (or the endpoint), but I think something like the following would be a good starting point:
```javascript
// /v2/characters/:id/sab/unlocks
[
  {
    id: 1,
    unlocked: true
  },
  {
    id: 2,
    unlocked: false
  },
  {
    id: 6,
    unlocked: true,
    quantity: 9
  }
]

// /v2/sab/unlocks?ids=all
[
  {
    id: 1,
    name: "Pointy Stick"
  },
  {
    id: 2,
    name: "Chain Sticks"
  },
  {
    id: 6,
    name: "Health Potion"
  }
]
```

A downside to this format is that, if SAB gets expanded upon, secrets will not stay a secret for long if they are exposed this way in `/v2/sab`. Maybe an auto-whitelist is an idea like the achievements have, but I'm not sure if it's feasible (it most likely isn't). Another possibility is to have a similar format like `/v2/account/home/cats`.

**Comment by lye** [comment]
It's almost certainly going to work like `/v2/account/home/cats` -- if only because that makes maintenance a bit easier. Like cats, the SAB stuff is implemented almost wholly in scripts and gameplay code rather than having structured data so there's nothing to throw into `/v2/sab`.
