### ISSUE TITLE
Add achievement group/category ids to each achievement in authenticated achievement endpoint

### ISSUE THREAD

**Issue by madou** [arenanet/api-cdi#483]
Hi !

So this is just a thought - but while I'm implementing achievements for gw2armory.com I'm running into a hitch where I have to load _all_ groups and categories before I can start grouping users achievements.

What I want to do is only load the groups and categories for the achievements the user has (paginated), but I can't really figure out the group and category for each achievement individually.

So atm it just has a big upfront data fetch to get them, not sooo bad, but it's just data I don't need until the user clicks "show all achievements" - or something similar!

Keen to discuss!

**Comment by lye** [comment]
Pulling all [groups](https://api.guildwars2.com/v2/achievements/groups?ids=all) (51KB, 12KB gzip'd) and [categories](https://api.guildwars2.com/v2/achievements/categories?ids=all) (3KB, 1KB gzip'd) is only two requests and <20KB on the network. I'm not really seeing the use-case.

There might be an argument to be made for adding the group/category information to `/v2/achievements` but honestly it's going to be faster to just fetch `{groups, categories, account-achievements}` in parallel than doing `account-achievements -> achievements -> {groups, categories}` in series.

**Comment by madou** [comment]
Sounds reasonable! And yeah, lapse of judgement, this definitely makes more
sense being added to V2/achievements.

How often are new achievement groups/categories added? Only down side of
this is figuring out when to get the data, atm it would be once a week...

**Comment by lye** [comment]
Groups almost never. Usually each release has a category or two for e.g. living world episode achievements.
