### ISSUE TITLE
Revenge of the Capricorn BETA: floors in v2/maps but not in v2/continents

### ISSUE THREAD

**Issue by ChieftainAlex** [arenanet/api-cdi#485]
[maps endpoint](https://api.guildwars2.com/v2/maps?ids=1163) suggests that Revenge of the Capricorn BETA" (map 1163) can be found on floors 0,1,2,8. 

[continents endpoint](https://api.guildwars2.com/v2/continents/2/floors?ids=2) returns ids invalid for floor 2.

i.e. v2/maps contains floors for which the given map_id doesn't appear in for v2/continents

They should probably tie up - I'm going to take a wild guess that floor 2 is where you put beta maps.

**Comment by ChieftainAlex** [comment]
Kind of related to the inverse of the above, some maps appear on more floors than v2/maps indicates.

:point_up: [April 5, 2017 8:26 PM](https://gitter.im/arenanet/api-cdi?at=58e544c98fcce56b20d30de0)

**Comment by ChieftainAlex** [comment]
SAB is also one of these weird ones. https://api.guildwars2.com/v2/maps?ids=895 but not in https://api.guildwars2.com/v2/continents/1/floors?ids=21

**Comment by lye** [comment]
This ... I think I may have fixed this.

The layer that reads content from the dat file was injecting floors `0, 1, 2` into maps that don't have any floors beyond the default floor. I'm not ... entirely sure why it was doing that, so I made the API's content service sidestep that behavior. So when this lands, Capricorn should have one floor (8).

It's not clear to me why SAB isn't in `/v2/continents`; that's probably an unrelated issue 🤢

**Comment by lye** [comment]
The SAB bits are all kinds of wonky so I'm going to punt on those.

**Comment by lye** [comment]
Have no idea what's wrong with SAB, but I kind of don't want to touch SAB stuff.

The Capricorn map is fixed, though.

**Comment by lye** [comment]
So the fix for this removed the upper floors from Divinity's Reach (and a bunch of other maps).

Got a different fix in the pipeline that adds the implicit 0-3 floors back where it makes sense. Effectively the new version inspects `/v2/continents/.../maps` and makes it consistent with `/v2/maps.floors`. Not sure why I didn't do it this way to begin with, whoops.

**Comment by lye** [comment]
The default floors for DR should now be appearing again (and Capricorn's default but nonexistent floors are still removed).
