### ISSUE TITLE
SSL certificate for render.guildwars2.com expired

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#488]
Not sure if this is the right place to report it, but the certificate used on render.guildwars2.com expired Wednesday, 12 April 2017 at 01:51:50 Central. It looks like api.guildwars2.com was using the same certificate, but has been updated with a new certificate that expires 3 years from now.

**Comment by darthmaim** [comment]
See https://forum-en.guildwars2.com/forum/community/api/Render-and-Tile-images-service-error/6551903:

> We have the new cert but ran into some issues getting it installed tonight. Everybody’s pretty beat so it’ll go in as soon as we can tomorrow.
> Sorry, this got missed in our checklists of places to updated certs. We’ll make sure it doesn’t happen again.

**Comment by hackedd** [comment]
Hmm, not sure how I missed that one...

**Comment by tivac** [comment]
Thanks for the report though!
