### ISSUE TITLE
v2/continents: Temples in orrian maps

### ISSUE THREAD

**Issue by ChieftainAlex** [arenanet/api-cdi#512]
Having a look at the Cursed Shore in v2/continents: https://api.guildwars2.com/v2/continents/1/floors/1/regions/3/maps/62

You can see that there is already one marker which is non-standard, the dungeon marker - and it specifies its own icon. Could that output be replicated for the temples too? Using Cursed Shore as an example, "Temple of Grenth" and "Temple of Melandru" should be there.

Ingame reference image: https://wiki.guildwars2.com/wiki/File:Cathedral_of_Verdance_map.jpg (light blue icon beneath the POI).

**Comment by lye** [comment]
I'll have to look into that. It's possible that the marker is placed via a map script -- pulling the location of it into the API may be unfeasible in that case, but at the very least I can dig up the icon for `/v2/files`.
