### ISSUE TITLE
Achievement category has duplicate achievement ids

### ISSUE THREAD

**Issue by madou** [arenanet/api-cdi#517]
See:
https://api.guildwars2.com/v2/achievements/categories/97

1839 is duplicated.

I believe this affects other categories too.

was yesterdays achievements unfortunately so its gone now - but still!

**Comment by madou** [comment]
ahhh - its gone now. weird. WAT?

**Comment by lye** [comment]
Happen to know if it was duplicated in-game as well? I can't recall how the
category data is structured, but it may just be in a list twice or
something. I'll be able to check what it was yesterday tomorrow morning /
"today".

**Comment by madou** [comment]
not sure if it was ingame.

**Comment by lye** [comment]
Fix for this should be live.
