### ISSUE TITLE
Map Tiles Are Out of Date

### ISSUE THREAD

**Issue by FrederikNS** [arenanet/api-cdi#52]
Is there any chance we can get some updates map tiles for the Tile API?

It still doesn't have the updates Lion's Arch.

**Comment by darthmaim** [comment]
https://forum-en.guildwars2.com/forum/community/api/World-map-tile-service-New-Lion-s-Arch/first#post5210524
> Probably not anytime soon; we’ve had a lot of issues with it.
> *coughs at Verdant Brink*

**Comment by FrederikNS** [comment]
Sooo... Now that HoT is out... :-P

**Comment by FrederikNS** [comment]
Ooooh! they just started coming through! Thanks
