### ISSUE TITLE
Skills that break stun don't list that in their "Facts"

### ISSUE THREAD

**Issue by windwarrior** [arenanet/api-cdi#528]
Skills that break stun don't list this in their facts, for example [Head Butt](https://api.guildwars2.com/v2/skills/30343) and [Elixir S](https://api.guildwars2.com/v2/skills/5861)

**Comment by madou** [comment]
woo!

**Comment by lye** [comment]
Weird, doesn't seem like that was ever emitted correctly. Added a new fact which looks like

```
      {
        "text": "StunBreak",
        "type": "StunBreak",
        "icon": "https://render.guildwars2.com/...",
        "value": true
      }
```

should go out in the future.

**Comment by madou** [comment]
neat! thanks lye

**Comment by Archomeda** [comment]
I think this went live to (at least) the above mentioned skills.
