### ISSUE TITLE
/v2/wvw/objectives: langor/bravost coordinates wrong

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#539]
[Forum ref](https://forum-en.guildwars2.com/forum/community/api/API-errors-bugs/6607596).

They're [currently the same](https://api.guildwars2.com/v2/wvw/objectives?ids=38-22,38-15) which can't be right. Most likely a bug in the script parsing code since I _think_ that's where the coordinates are coming from.

**Comment by Archomeda** [comment]
[Archived forum ref.](https://gw2developers.github.io/forum-backup/API-errors-bugs/)

It seems that the coordinates are different now. Probably fixed?
