### ISSUE TITLE
Add SAB achievement categories to achievement groups

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#544]
The categories for SAB achievements ([22, 45, 46](https://api.guildwars2.com/v2/achievements/categories?ids=22,45,46)) are missing in the achievement groups:
https://api.guildwars2.com/v2/achievements/groups?ids=all

CTRL + F for the category ids, they are not linked to any group.

---

Forum Ref: https://forum-en.guildwars2.com/forum/community/api/Achievement-points-totally-wrong

**Comment by Archomeda** [comment]
[Archived forum ref.](https://gw2developers.github.io/forum-backup/Achievement-points-totally-wrong/)

**Comment by queicherius** [comment]
Closing in favor of #600
