### ISSUE TITLE
Missing POI in Rata Sum and the Grove

### ISSUE THREAD

**Issue by zellerda** [arenanet/api-cdi#552]
I use this query to get map items
https://api.guildwars2.com/v1/map_floor.json?continent_id=1&floor=1
Only 8 landmark in Rata Sum instead of 19
Only 5 landmark in The Grove instead of 19

I do some research and it's appear that the missing landmark appear if we change the floor option in the query, but why the Divinity Reach has all landmark with floor = 1, same for the Black Citadel and Hoelbrak.

That will be great if all landmark will be available with floor = 1 for Rata Sum and The Grove, because make 4 queries to get all markers is too long, about 10 seconds. The best will be to add the possibility to query only one map by it's ID, like this https://api.guildwars2.com/v1/map_floor.json?continent_id=1&floor=1&map_id=139.

I know, I can use this query (https://api.guildwars2.com/v1/maps.json?map_id=139) but there is not POI returned.

**Comment by ChieftainAlex** [comment]
Wow version 1. You know there's a version 2 of the API too right?

Having said that, even with https://api.guildwars2.com/v2/continents/1/floors?ids=all , collating the information common between floors is still tedious.

```
// Example for continent 1 only.
// Get metadata information
$.getJSON('https://api.guildwars2.com/v2/maps?ids=all', function(maps){
  // Rearrange metadata info by map id
  var mapdata = {};
  $.each(maps, function(i,v){
    mapdata[v.id] = v;
    mapdata[v.id]['points_of_interest'] = {};
  });

  // Get detailed information
  $.getJSON('https://api.guildwars2.com/v2/continents/1/floors?ids=all', function(data){
    $.each(data, function(fi,floorv){
      $.each(floorv['regions'], function(ri, regionv){
        $.each(regionv['maps'], function(mi, mapv){
          var mapid = mapv.id;
          $.each(mapv['points_of_interest'], function(pi, poiv){
            if (!(poiv.id in mapdata[mapid]['points_of_interest'])) {
              mapdata[mapid]['points_of_interest'][poiv.id] = poiv;
            }
          });
        });
      });
    });

    // Remove maps without any points of interest
    $.each(mapdata, function(k,v){
      if (Object.keys(v['points_of_interest']).length === 0) {
        delete mapdata[k];
      }
    });
    console.log(mapdata);

    // Test Rata Sum (map id 139)
    var landmarkcount = 0;
    $.each(mapdata[139]['points_of_interest'], function(k,v){
      if (v.type == 'landmark') { landmarkcount += 1; }
    });
    console.log('There are ' + landmarkcount + ' landmarks in Rata Sum (map 139)');
  });
});
```

**Comment by zellerda** [comment]
Ok thanks for your answer, I will check that
