### ISSUE TITLE
Incorrect text in daily fractal achievements response

### ISSUE THREAD

**Issue by tobaroni** [arenanet/api-cdi#554]
Nightmare and Chaos fractals have incorrect scales in their description for "daily tier fractal" achievements.

Affected IDs are:
Nightmare: 3229,3196,3175,3177
Chaos: 3063, 3044, 3045, 3038

**Comment by Archomeda** [comment]
It seems that the descriptions have been removed entirely now: https://api.guildwars2.com/v2/achievements?ids=3229,3196,3175,3177,3063,3044,3045,3038

I guess you can call this fixed?
