### ISSUE TITLE
Material storage has wrong item order

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#556]
Some of the items in the material storage API are not in the order they are ingame. An example of this is "Lump of Glass" ([75075](https://api.guildwars2.com/v2/items/75075)), which is somewhere in the middle ingame ...

![](http://i.imgur.com/ah5wmYv.png)

... but on the [`/v2/materials` API](https://api.guildwars2.com/v2/materials?ids=6&lang=en) it's the very last:

![](http://i.imgur.com/LbHY3pP.png)

**Comment by queicherius** [comment]
Fixed itself at some point.

**Comment by Archomeda** [comment]
This issue has reappeared again.
![materials](https://user-images.githubusercontent.com/1467127/40392539-46d52d02-5e1c-11e8-96ff-4291e1392625.png)

**Comment by dsnider-anet** [comment]
This should be fixed. see https://api.guildwars2.com/v2/materials/46
