### ISSUE TITLE
PoF issues

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#557]
<p align="center">
    <img src="https://user-images.githubusercontent.com/2511547/29379247-1e9c7e5c-82c2-11e7-8f09-33ae2b0cb1f3.png">
</p>

PoF is breaking a few things in the API, here is a list:

* **/v2/account `access`**  
Currently still lists `HeartOfThorns`. Additionally, PoF can be bought independently of HoT, so we either need to use `HeartOfThornesAndPathOfFire` as value, or add a new property (`accesses`. `expansions`, ...) that is an array of all available expansions.  
Probably a good idea to also check if `required_access` in /v2/achievements/daily is still working correctly.
* ~~**/v2/profession/Elementalist dual attunements**~~ ✔︎  
The new elite spec Weaver has different skills in the `Weapon_3` slot depending on the dual attunement. We need a new property (`weaver_attunement`?) that works like the thiefs `offhand` property.
* **Some traits are missing descriptions**
Some traits are missing the description in the API ([examples](https://api.guildwars2.com/v2/traits?ids=2075,2101,2086,2062,2063,2076,2116,2148,2105,2179,2159,2166,2079,2120,2154,2092,2108,2142,2094,2100,2182,2134,2071,2072,2156,2119,2085,2161,2127,2155,2143) from [the forum](https://en-forum.guildwars2.com/discussion/21971/some-traits-have-no-description-field)).

**Comment by lye** [comment]
:fire:

**Comment by jerherrero** [comment]
I might have one to add.
**- /v2/characters**
In this query, PoF demo characters are included in the list of characters. However, there does not appear to be a way to differentiate these demo characters from normal characters.

**Comment by queicherius** [comment]
@jerherrero 

Since recently, demo characters have an additional flag:

```js
{
  "name": "Vicona Demo",
  "race": "Human",
  "gender": "Female",
  "flags": [
    "Beta"
  ],
  ...
}
```

**Comment by jerherrero** [comment]
More than half the time all of my characters have a "Beta" flag on it. This is the case even if I open the API url via my web browser.

**Comment by Aonwy** [comment]
Beta characters should no longer be an issue, as we wiped them all from the servers. 
Going to close this one as we have duplicates for the other 2 bugs. Anything new that crops up should get its own bug for action.
