### ISSUE TITLE
Provide a flag to allow catching skill type

### ISSUE THREAD

**Issue by valento92** [arenanet/api-cdi#562]
From this example:
https://api.guildwars2.com/v2/skills?ids=13114&lang=en

Would it be possible to insert some way to catch the skill type so we can customize it? Like recolor it like in-game. Maybe `<@skill-type>Stealth Attack.</skill-type>`.

Thank you!

**Comment by madou** [comment]
^ would be fantastic if we could get it wrapped like that.

**Comment by valento92** [comment]
It would be nice to wrap signet texts too, like `<@skill-type>Signet Passive:</skill-type>` and `<@skill-type>Signet Active:</skill-type>`. Don't forget including the period and colon! :D

**Comment by apoch** [comment]
I'd like to understand this request better, if it's still something you're interested in having.

My perspective is that you can retrieve some JSON that describes a skill; you can traverse that JSON object to locate the "categories" element, and you can see the existing set of values like `StealthAttack` that are put in that array.

Again, from my perspective, it seems like you should be able to emit any text you want at this point. You know you are parsing skill object JSON, you know you're reading the skill categories, and you know what the set values (`StealthAttack`) should translate into (`<@skill-type>Stealth Attack</skill-type>`)

What am I missing here? :-)

**Comment by valento92** [comment]
Oh, I believe that should suffice. Unless someone else has something extra to add, I think the tools are already there. Thank you.
