### ISSUE TITLE
Mastery points for "Tyria" disappeared out of /account/mastery/points

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#566]
Previously, on [/account/mastery/points](https://api.guildwars2.com/v2/account/mastery/points?access_token=BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041) you could read out the mastery points of both regions, "Maguuma" and "Tyria". Now, only "Maguuma" is showing up, and" Tyria" is missing ([for all API keys, as far as I can tell](https://gw2efficiency.com/account/statistics/statistics.masteryPointsTyria)).

**Comment by lye** [comment]
:cry:

**Comment by queicherius** [comment]
This seems to have fixed itself at some point.
