### ISSUE TITLE
Missing home instance nodes in /v2/account/home/nodes

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#567]
The following nodes are missing from `/v2/account/home/nodes` (and `/v2/nodes`):

- Advanced Leather Rack
- Advanced Cloth Rack
- Black Lion Hunter's Board
- Orrian Oyster Node
- Anything added after that...

**Comment by Archomeda** [comment]
A few more things have been added:

- Brandstone Node (#590)
- Black Lion Garden Plot Deed (a two-time upgrade, for now)

And a few "toys" that were already there, but aren't available on the API yet:
- Feline Dispersing Emitter
- Feline Holoscepter
- Feline Water Pistol

Although I don't know whether `/v2/cats` is a better place for them. But I have a feeling that they technically are "upgrades" (which mean "nodes" for the API) and not "cats".

**Comment by dsnider-anet** [comment]
Garden plot is a bit tricky since it can be upgraded twice. A quick solution is possible in the short-term: show that a player has unlocked any of the garden plots at all but not how many.

```js
[
  // ...
  "garden_plot",
  // ...
]
```

If we wanted to show both plots, I think it might be easy to show it like so:

```js
[
  // ...
  "garden_plot_1",
  "garden_plot_2",
  // ...
]
```

We could go even further, break the schema and say:

```js
[
  // ...
  {"garden_plots": 2},
  // ...
]
```

But that's harder on this end and arguably not that useful.

Thoughts?

**Comment by queicherius** [comment]
```
[
  // ...
  "garden_plot_1",
  "garden_plot_2",
  // ...
]
```

seems like the sanest solution

**Comment by queicherius** [comment]
With the release today only the garden plot and the bauble gathering system are missing 💯

**Comment by dsnider-anet** [comment]
`bauble_gathering_system` has been added.
Garden plot is still missing

see https://api.guildwars2.com/v2/nodes

**Comment by Archomeda** [comment]
New home instance node: [Supply Cache](https://wiki.guildwars2.com/wiki/Supply_Cache_(item)).

**Comment by queicherius** [comment]
Just to update, all nodes that got released since the last node update for the API are missing.

**Comment by dsnider-anet** [comment]
This should be fixed.
The static endpoint for available nodes is here: https://api.guildwars2.com/v2/home/nodes

**Comment by queicherius** [comment]
Missing: 

- https://wiki.guildwars2.com/wiki/Dragon_Crystal_Home_Instance_Node
- https://wiki.guildwars2.com/wiki/Mistborn_Mote_Home_Instance_Node

**Comment by queicherius** [comment]
Also, now missing again:

- Black Lion Hunter's Board
- Black Lion Expedition Board

**Comment by queicherius** [comment]
Also the new one:

- Eternal Ice Node

**Comment by queicherius** [comment]
Now all seem to be live 🎉 Thanks!
