### ISSUE TITLE
Parts of legendary WvW/PvP armors missing in /v2/items

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#568]
While the legendary armours for WvW and PvP have been out for a while, `/v2/items` is still missing some of their parts, possibly because nobody crafted these specific parts yet, so they are not in the whitelist?

[Here is the list of items with their ascended and legendary ids.](https://gist.github.com/queicherius/e7fe50ae19479927de48f327a80e3558)

**Comment by queicherius** [comment]
Just pinging here to let you know that I updated the sheet of items. There are still 13 items missing in the whitelist.

**Comment by queicherius** [comment]
Pinging again, still 9 items missing.

**Comment by ChieftainAlex** [comment]
Checked + all the identified items are whitelisted, this could be closed.
