### ISSUE TITLE
Path of fire mastery points are called "Unknown" in v2/achievements

### ISSUE THREAD

**Issue by madou** [arenanet/api-cdi#577]
See: https://api.guildwars2.com/v2/achievements/3644

```
"rewards": [
  {
    "type": "Mastery",
    "region": "Unknown",
    "id": 409
  }
]
```

**Comment by ChieftainAlex** [comment]
Pretty sure Lye has added the Desert to the acceptable regions within the content (not api) and this should therefore be fixed with the next major ingame content patch.

**Comment by madou** [comment]
fixed.
