### ISSUE TITLE
Server links are incorrect

### ISSUE THREAD

**Issue by seasniffer** [arenanet/api-cdi#584]
https://api.guildwars2.com/v2/wvw/matches/1-2

Still showing last pairings links in the all_worlds field and it's been a few weeks since relink.

**Comment by Archomeda** [comment]
Actually, right now it's showing duplicated worlds on the match you linked:

```js
{
  "id": "1-2",
  "start_time": "2017-12-16T02:00:00Z",
  "end_time": "2017-12-23T01:58:00Z",
  // ...
  "worlds": {
    "red": 1003,
    "blue": 1009,
    "green": 1005
  },
  "all_worlds": {
    "red": [
      1013,
      1003
    ],
    "blue": [
      1023,
      1009
    ],
    "green": [
      1023,
      1005
    ]
  },
  // ...
}
```

I'm not sure what this is actually supposed to be right now, but it seems wrong 😛
