### ISSUE TITLE
ErrBadData

### ISSUE THREAD

**Issue by Faedrivin** [arenanet/api-cdi#59]
For a while (can't specify further, but at least a few hours) the API calls to https://api.guildwars2.com/v2/characters?access_token=6C5DE92F-65FF-2042-AC3B-87B1C788A0D7DE0065BF-95FB-45C1-A458-06AA0064268E return {"text":"ErrBadData"} and/or HTTP Status 400. Could be it is just temporary issue or that the beta somehow affects my account.
I tried different keys as well.

**Comment by RedGlow** [comment]
It's giving me the same problem right now, with the request https://api.guildwars2.com/v2/account/materials?access_token=3FA6BCE3-7251-2B44-ABF6-DDE86089918256C9C214-59B2-456E-ADF4-78EB81B2E6D7 (and with the original URL too)

**Comment by lye** [comment]
Ah, looks like Friday night's hotfix broke something. Really sorry about that, we'll have it fixed on Monday.

**Comment by lye** [comment]
This should be fixed now.
