### ISSUE TITLE
Achievement ID 3219 missing

### ISSUE THREAD

**Issue by commonquail** [arenanet/api-cdi#592]
Achievement ID 3219 [is missing from /v2/achievements](https://api.guildwars2.com/v2/achievements?ids=3219&lang=en):

> 299 api.guildwars2.com "Unknown id 3219" "Sun, 03 Dec 2017 08:55:57 GMT"

That ID is included in today's /v2/achievements/daily and based on the in-game UI the achievement should probably have been *Daily Recommended Fractal—Scale 69*.

Since the Daybreak patch a few *Daily Recommended Fractal* achievements have been missing so I don't think this is the only one, though I don't have other IDs at hand. Curiously, scale 69 was not changed in that patch (1-7, 16, 41, 59, and 87 were).

**Comment by Archomeda** [comment]
This can be closed, the achievement is now available on the API.
