### ISSUE TITLE
/v2/pvp/seasons is missing season 9

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#593]
[/v2/pvp/seasons?ids=all](https://api.guildwars2.com/v2/pvp/seasons?ids=all) is missing season 9

It is also missing in /v2/pvp/standings, but not in /v2/pvp/games (season id is `99373A3D-1E25-447C-9E18-C347871AF239`)

**Comment by lye** [comment]
Season 10 should additionally appear in a timely fashion.
