### ISSUE TITLE
Mesmer profession skills

### ISSUE THREAD

**Issue by xmort04** [arenanet/api-cdi#595]
All Mesmer professions skills ("Mind Wrack", "Cry of Frustration", "Diversion", "Distortion", "Continuum Shift", "Continuum Split") have empty array in attribute "professions":
`    "professions": [],`
hence it is not possible to assign them to Mesmer automatically.

**Comment by darthmaim** [comment]
This was fixed. https://gitter.im/arenanet/api-cdi?at=5aa13d05888332ee3a13871b

**Comment by dsnider-anet** [comment]
Fixed.
see, e.g.: https://api.guildwars2.com/v2/skills/10192

```js
{
"name": "Distortion",
// ....
"professions": [
"Mesmer"
],
// ...
}
```
