### ISSUE TITLE
/v2/account/mastery is missing PoF mastery totals

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#599]
[/v2/account/mastery](https://api.guildwars2.com/v2/account/mastery/points?access_token=BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041) is missing the totals for PoF mastery achievements (there should be a total with the region `Desert`)

**Comment by queicherius** [comment]
This happened between [**24 Jan 2018 11:26** and **25 Jan 2018 06:18**](https://i.imgur.com/v0XNU51.png) for [all accounts](https://gw2efficiency.com/account/statistics/statistics.masteryPointsDesert).

**Comment by queicherius** [comment]
The reappeared on 7th of February but since it happened before there might be an underlying issue

**Comment by Aonwy** [comment]
Without a repro we cannot confirm whether we have found and corrected any possible underlying issues. Please let us know here if this reoccurs.

**Comment by queicherius** [comment]
It is reoccurring: [May 3, 2018 2:22 PM](https://gitter.im/arenanet/api-cdi?at=5aeb0d0ce2d30c2f045fe596)
