### ISSUE TITLE
Buy/sell orders for tradingpost transactions are not updated

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#605]
Buy/sell orders have not been updated since early January for select accounts. This was discussed in Gitter multiple times before, but I just saw that we didn't have a tracking ticket.

![](https://i.imgur.com/GL1WekY.png)

**Comment by Kakirtog** [comment]
Got this issue too, mine haven't updated in 2 months:
455152A1-4E3A-A842-A5EA-D2905AA76E48FD000E79-99BE-45FB-9291-89026D05C32C

**Comment by Silveress** [comment]
My sell orders have been frozen for a while and buy orders stopped wortking a few days ago AF8091DD-8825-024D-8A37-7812B66597D8F41F2EA9-BE47-4D9E-B79B-ED1621506E20

**Comment by queicherius** [comment]
Just to be clear, this is both for current and historic orders.

**Comment by dsnider-anet** [comment]
This should be fixed. To verify:
* list an item on the trading post
* wait > 1min
* access https://api.guildwars2.com/v2/commerce/transactions/current/sells
* observe that transaction appears

**Comment by queicherius** [comment]
Seems to work just fine! 🎉
