### ISSUE TITLE
Tradingpost API can return wrong page number

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#606]
Sometimes the tradingpost api (specifically `/v2/commerce/transactions/`) returns wrong page headers and wrong error messages:

Example of being on **page 46** and the header then showing that there are **48 pages**:

![](https://i.imgur.com/nM0p9ZQ.png)

Then (for the same API key) on **page 48** it throws an error that the maximum page is **45** (even tho we just successfully read from page 46):

![](https://i.imgur.com/SYtapQ0.png)

**Comment by jechase** [comment]
Just a note: If the page total is 48 and the pages are 0-indexed, then page 48 will actually be at `page=47`.

Regardless, I'm seeing similar behavior.

When `page_size=200` and `page=0`, `x-page-total` is 3, but when `page=1` is fetched, `x-page-total` changes to 2, and `page=2` returns a 400 error.

I would post a log of commands needed to reproduce this, but it seems that when I was preparing the failing example, the issue resolved itself for my account :confused:

**Comment by queicherius** [comment]
I have not seen this issue pop back up in the last 10 days, so I'm going to assume it fixed itself :)
