### ISSUE TITLE
Gold to gem prices not updating since January 2018

### ISSUE THREAD

**Issue by werdes** [arenanet/api-cdi#614]
So apparently there wasn't an issue for this.

Gold to Gem prices seem to be broken since January 11th 2018 (compare examples), constantly displaying the same result (https://api.guildwars2.com/v2/commerce/exchange/coins?quantity=250000).
Apparently there were some flickers in late January, but it flatlined after (https://en-forum.guildwars2.com/discussion/25771/gold-to-gem-prices-are-not-working).

**Examples:**
- https://gw2efficiency.com/currencies/gems
- http://www.gw2spidy.com/gem

**Comment by queicherius** [comment]
Just so that is no confusion: gw2e shows the gem history **from gw2spidy** (via their API). I am fairly sure that it's just a gw2spidy bug and the API is working - since the price in the API response does not match the price in the graph.

**Comment by werdes** [comment]
seems plausible. That forum thread stirred quite a lot of confusion 🤔
