### ISSUE TITLE
Prevent Unobtainable Data from being Auto-Whitelisted

### ISSUE THREAD

**Issue by CuriousCharr** [arenanet/api-cdi#617]
Where...
+ "Data" refers to all content served by the JSON API Endpoints; be it an Item, a Mini, a Color or anything else)
+ "Unobtainable Data" refers to "Test Data" and "Spoiler Data"
+ "Test Data" refers to "Data" not obtainable in Game by any means, to the "General Audience"
+ "Spoiler Data" refers to "Data" not obtainable in Game, to the "General Audience", yet; witch altough then would be made available at a later Point in Time (probably aka. Leaked Data)
+ "General Audience" refers to everyone not working at ArenaNet who Plays Guild Wars 2.

How it is at the moment:
At the moment various Endpoints (e.g.: /v1/item_details.json, /v2/items and /v2/minis (as well as /v1/item_details.json respectively) see #601 ) include Test Data in there Responses, thanks to Auto-Whitelisting.
I'm not aware of any Endpoint that includes Spoiler Data at the moment, but such Data showing up should be prevented (if not already taken care of) before it comes up.
Furthermore, the currently included Test Data at the Endpoints requires to maintain a local Whitelist (or possibly a Blacklist instead) if an Application would only want to show currently in Game obtainable Data from a given Endpoint.

How it would be better:
As many Endoints as possibly feasable should maintain up to date Auto-Whitelists that reliably exclude Unobtainable Data as well as references to such Data.
This would prevent Data Leaks originating from Endpoints as well as possible confusion by the presence of Test Items.
It would also remove the need to maintain local White/Blacklists in case only actually in Game obtainable Data should be Displayed.

**Comment by Aonwy** [comment]
We have discussed this multiple times over the past year in various other reports and venues, and our perceived consensus from users has been that they would rather have access to the new data as it is made available, rather than going back to the system where new data lagged (sometimes significantly), but test data was not included. 

I am going to close this, unless the community feels strongly that this issue needs to be reopened for additional discussion.

**Comment by CuriousCharr** [comment]
Hm.. i can understand that.
I would have tought more of adjusting the existing Auto Whitelisting in such a way that prevents it to also Whitelist Test Data, instead of going back to not having Auto Whitelsisting at all, but ok.

So then, if Test Data isn't going to be removed and more might appear in the future, would it then instead be possible to include a Flag to everything that is to be considered Test Data, such that it can be more easily filtered out Programmatically? (e.g. `"test_data":true`, `"obtainable":false` or `"scope":"TestDataOnly"`)
If so, let me know then i'll create an Issue for it.
