### ISSUE TITLE
/v2/colors is missing Colors avaiable in Kits

### ISSUE THREAD

**Issue by CuriousCharr** [arenanet/api-cdi#624]
Where...
"Kit" refers to [Total Makeover Kit](https://wiki.guildwars2.com/wiki/Total_Makeover_Kit) and partially [Self-Style Hair Kit](https://wiki.guildwars2.com/wiki/Self-Style_Hair_Kit).

At the moment only a subset of the Colors avaiable in Kits seem to appear in /v2/colors. The other Colors (as e.g. Medium Blue, Foofoo, Panther Black, Pale Orange/Yellow/..) do not.

It is to be expected /v2/colors to either contain all or none of the, non Kit-Exclusive, Colors.

/v2/colors should at least List all of the non Kit-Exclusive Colors, and not only Part of them.

<details>
<summary>Legend [missing/total]</summary>

Lines starting with '+' indicate that the Color is avaiable in both Kits and /v2/colors
Lines starting with '-' indicate that the Color is avaiable only in the Kits but is missing in /v2/colors
Colors Listed are Limited to those Colors witch are NOT explicitly marked as Exclusive to the Makover Kits. (those withouth the Star)

Spelling Mistakes Copyright (c) me. Do not change.
</details>

<p></p>

<details>
<summary>Fur-/Pattern-/Hair- Colors [29/35]</summary>

+Black
+Chocolate
+Sienna
+Pale
+Sand
+White
-Panther Black
-Burnt Toast
-Coffee
-Red Brown
-Foofoo
-Red Orange
-Tiger Orange
-Yellow
-Pale Orange
-Light Orange
-Mesh
-Soft Yellow
-Pale Yellow
-Fried
-Pale Orche
-Orche
-Verry Dark
-Dark Gray
-Dark Bobcat
-Medium Bobcat
-Bobcat
-Dark Sand
-Tiger White
-Peach Gray
-Gray Wolf
-Payne's Gray
-Blue Gray
-Snow Gray
-Snow White
</details>

<p></p>

<details>
<summary>Eye- Colors [36/43]</summary>

+Black
+Gray
+White
+Orange
+Red
+Pink
+Purple
-Autumn Brown
-Chestnut Brown
-Medium Brown
-Light Brown
-Pale Brown
-Goldenrot
-Pale Yellow
-Yellow
-Bright Yellow
-Sunlight
-Pale Orange
-Bright Orange
-Light Orange
-Loud Organe
-Dark Red
-Pale Pink
-Pale Purble
-Bright Purple
-Light Purple
-Bluebell
-Dark Blue
-Bright Blue
-Ice Blue
-Light Blue
-Sky Blue
-Blue
-Medium Blue
-Blue Green
-Pale Blue
-Pale Blue Green
-Green Mist
-Mint Green
-Pale Green
-Light Green
-Medium Green
-Leaf Green
</details>

<p></p>

<details>
<summary>Acessory- Colors [0/21]</summary>

+Orchid
+Royal Rose
+Glory
+Tea Jeans
+Stream
+Winter Sky
+Jalapeno
+Limette
+Deep Maple
+Autumn
+Salmon
+Apricot
+Antique Gold
+Pottery
+Clay
+Camel
+Dijon
+Ebony
+Tarnished Steel
+Stone
+Matte
</details>

**Comment by Aonwy** [comment]
There are names that belong in both dye and color categories, but this list only exposes dyes that are available in-game. Anything else that appears to be missing, is so because it is not a dye and not something acquirable by players. There are actually no colors in that list, but there are things that use the same text as colors, hence the confusion around hair/eye colors. Technically the endpoint should probably be 'dyes' instead of 'colors', but in the interests of not breaking existent code we are going to leave it alone.

**Comment by CuriousCharr** [comment]
Even tough it's unfortunate to "hear" that the missing "Color"s can't be added; i do understand that this seemed to have been a misconception on my Side then, now that i know about there being more than one kind of "Color" and that the "Color"s i Listed are to be considered different from the "Dye"s already provided by /v2/colors acordingly.

Thanks for digging and considdering addition either Way. :)
