### ISSUE TITLE
Chronomancer profession skills are missing specialization property

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#625]
[Continuum Split](https://api.guildwars2.com/v2/skills/29830?lang=en) and [Continuum Shift](https://api.guildwars2.com/v2/skills/30747?lang=en) should include `specialization: 40` ([Chronomancer](https://api.guildwars2.com/v2/specializations/40?lang=en)).

**Comment by apoch** [comment]
These should be fixed.
