### ISSUE TITLE
RenderSrv returning errors

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#627]
The [`profession_icon`](https://render.guildwars2.com/file/B0A3C5B4097705AE21E9CB78E53045E327F1C7C9/1128569.png) and [`profession_icon_big`](https://render.guildwars2.com/file/4C919A74282939EC004333292A93A4073CCDFFFD/1128568.png) of the [Chronomancer elite spec](https://api.guildwars2.com/v2/specializations/40) both return this error:

```
{
  "error": 48,
  "product": 0,
  "module": 2,
  "line": 89,
  "text": "file couldn't be loaded"
}
```

Other elite spec profession icons might be affected too...

**Comment by Yoone** [comment]
Got the same error message/code when trying to load some icons from the items API (both on V1 and V2).

**Comment by Aonwy** [comment]
Is this still occurring?

**Comment by Yoone** [comment]
It is for me.

Could it be related to a hit rate? If I perform the call on two different IPs (two different countries), one of them will yield the error while the other one will display the icon.

The other theory I have in mind is that it could be a CDN issue.

**Comment by darthmaim** [comment]
This is still happening, even though the files that are broken seem to change from time to time. Currently https://render.guildwars2.com/file/5ED4EEB5ACE15B57EFE6371CB325063F74344B52/1991539.png and the other awakened mount skins can't be loaded.

Someone has made a [forum post](https://en-forum.guildwars2.com/discussion/41547/api-files) 1 day after I created this issue and posted a website that shows the files referenced in /v2/files: http://www.timscloud.uk/GW2/Icons/API1_Files.html. Roughly half of them return that error for me atm.

**Comment by Aonwy** [comment]
Thank you for posting with the additional information.

We think this is part of a larger pipeline issue, although we are still in the process of trying to identify the scope of the issue. There are several bugs in here that seem related, and we hope that fixing the underlying issue will fix these, too.

**Comment by peek4y** [comment]
Facing same issue, roughly 70% of the icons fail to load for me, I tried to connect via a VPN and tried to load icons, it worked.

**Comment by Yoone** [comment]
This issue is still happening for me. Any news @Aonwy?

**Comment by ChieftainAlex** [comment]
Both loading for me right now, so believe this is resolved.
