### ISSUE TITLE
Item ids not resolving

### ISSUE THREAD

**Issue by TheHexCode** [arenanet/api-cdi#632]
It looks like multiple item ids aren't resolving to their respective items. The one I specifically ran into was item id 12470, but even the two examples on the wiki (28445 and 12452) don't resolve to anything.

**Comment by TwiggyTwixter** [comment]
I have also found that item 19626 isn't resolving, and bringing up the entire items list it is actually missing from the API altogether

**Comment by BenLubar** [comment]
It looks like the entire API is broken right now: https://status.gw2efficiency.com/

**Comment by TheHexCode** [comment]
It looks like whatever was broken is fixed now, or at least everything I've been having problems with, I'm not anymore. If no one else is having problems, this can probably be closed.
