### ISSUE TITLE
Broken Caching on u.a. /v2/items and /v2/recipes

### ISSUE THREAD

**Issue by CuriousCharr** [arenanet/api-cdi#636]
This can be observed by running requests against e.g. /v2/items repeatedly using e.g. the following Python Scrypt:

<details>
<summary>Python Scrypt</summary>

```python
import requests as req
import random as rand
import time
import datetime
import json

while True:
    r = req.get('https://api.guildwars2.com/v2/recipes')
    r_end = datetime.datetime.utcnow()
    print(r.status_code, r_end.strftime('%Y-%m-%dT%H:%M:%SZ'), end=' ')
    data = r.json()
# Indend this to keep a history of the response data in a directory named "itemids"
#    with open('itemids/' + r_end.strftime('%Y-%m-%dT%H#%M#%SZ') + '.json', 'w') as f:
#        f.write(json.dumps(data, indent=True))
    print(len(data))
    time.sleep(3)
```
</details><br/>
This Scryptin specific will output something along the lines of the following; showing varius jumps in the ammount of item ids returned by /v2/items:<br/>
<br/>
<details>
<summary>Resulting Output /v2/items</summary>

200 2018-07-10T17:16:08Z 47165 
200 2018-07-10T17:16:12Z 47165 
200 2018-07-10T17:16:15Z 47165 
200 2018-07-10T17:16:19Z 47165 
200 2018-07-10T17:16:22Z 47165 
200 2018-07-10T17:16:26Z 47165 
200 2018-07-10T17:16:29Z 47165 
200 2018-07-10T17:16:33Z 47166 
200 2018-07-10T17:16:36Z 47165 
200 2018-07-10T17:16:40Z 47165 
200 2018-07-10T17:16:43Z 47166 
200 2018-07-10T17:16:47Z 47165 
200 2018-07-10T17:16:50Z 47165 
200 2018-07-10T17:16:53Z 47165 
200 2018-07-10T17:16:57Z 47165 
200 2018-07-10T17:17:00Z 47165 
200 2018-07-10T17:17:04Z 47165 
200 2018-07-10T17:17:07Z 47165 
200 2018-07-10T17:17:11Z 47165 
200 2018-07-10T17:17:14Z 47165 
200 2018-07-10T17:17:17Z 47165 
200 2018-07-10T17:17:21Z 47165 
200 2018-07-10T17:17:24Z 47165 
200 2018-07-10T17:17:28Z 47165 
200 2018-07-10T17:17:31Z 47165 
200 2018-07-10T17:17:35Z 47166 
200 2018-07-10T17:17:38Z 47165 
200 2018-07-10T17:17:42Z 47165 
200 2018-07-10T17:17:45Z 47166 
200 2018-07-10T17:17:49Z 47165 
200 2018-07-10T17:17:52Z 47166 
200 2018-07-10T17:17:55Z 47165 
200 2018-07-10T17:17:59Z 47165 
200 2018-07-10T17:18:02Z 47165 
200 2018-07-10T17:18:06Z 47165 
200 2018-07-10T17:18:09Z 47165 
...

200 2018-07-10T18:03:49Z 47178 
200 2018-07-10T18:03:52Z 47178 
200 2018-07-10T18:03:56Z 47177 
200 2018-07-10T18:03:59Z 47166 
200 2018-07-10T18:04:03Z 47177 
200 2018-07-10T18:04:06Z 47177 
200 2018-07-10T18:04:10Z 47178 
200 2018-07-10T18:04:13Z 47166 
200 2018-07-10T18:04:17Z 47177 
200 2018-07-10T18:04:20Z 47166 
200 2018-07-10T18:04:24Z 47178 
200 2018-07-10T18:04:27Z 47178 
200 2018-07-10T18:04:31Z 47177 
200 2018-07-10T18:04:34Z 47177 
200 2018-07-10T18:04:38Z 47177 
200 2018-07-10T18:04:41Z 47166 
200 2018-07-10T18:04:45Z 47166 
200 2018-07-10T18:04:48Z 47177 
200 2018-07-10T18:04:52Z 47177 
200 2018-07-10T18:04:56Z 47177 
200 2018-07-10T18:04:59Z 47166 
200 2018-07-10T18:05:03Z 47177 
200 2018-07-10T18:05:06Z 47166 
200 2018-07-10T18:05:10Z 47178 
200 2018-07-10T18:05:13Z 47178 
200 2018-07-10T18:05:17Z 47178 
200 2018-07-10T18:05:20Z 47178 
200 2018-07-10T18:05:24Z 47178 
200 2018-07-10T18:05:27Z 47177 
200 2018-07-10T18:05:31Z 47166 
200 2018-07-10T18:05:34Z 47177 
200 2018-07-10T18:05:38Z 47166 
200 2018-07-10T18:05:41Z 47178 
200 2018-07-10T18:05:45Z 47177 
200 2018-07-10T18:05:49Z 47178 
200 2018-07-10T18:05:52Z 47177 
200 2018-07-10T18:05:56Z 47177 
200 2018-07-10T18:05:59Z 47177 
200 2018-07-10T18:06:03Z 47177 
200 2018-07-10T18:06:06Z 47177 
200 2018-07-10T18:06:10Z 47177 
200 2018-07-10T18:06:14Z 47177 
200 2018-07-10T18:06:17Z 47177 
200 2018-07-10T18:06:21Z 47177 
200 2018-07-10T18:06:24Z 47177 
200 2018-07-10T18:06:28Z 47178 
200 2018-07-10T18:06:31Z 47178 
200 2018-07-10T18:06:35Z 47177 
200 2018-07-10T18:06:38Z 47178 
200 2018-07-10T18:06:42Z 47177 
200 2018-07-10T18:06:45Z 47178 
200 2018-07-10T18:06:49Z 47177 
200 2018-07-10T18:06:52Z 47177 
200 2018-07-10T18:06:56Z 47177 
200 2018-07-10T18:06:59Z 47178 
200 2018-07-10T18:07:02Z 47178 
200 2018-07-10T18:07:06Z 47178 
200 2018-07-10T18:07:11Z 47177 
200 2018-07-10T18:07:14Z 47177 
200 2018-07-10T18:07:18Z 47177 
200 2018-07-10T18:07:21Z 47177 
200 2018-07-10T18:07:25Z 47177 
200 2018-07-10T18:07:28Z 47177 
200 2018-07-10T18:07:32Z 47178 
200 2018-07-10T18:07:36Z 47177 
200 2018-07-10T18:07:39Z 47177 
200 2018-07-10T18:07:43Z 47178 
200 2018-07-10T18:07:46Z 47178 
200 2018-07-10T18:07:50Z 47178 
200 2018-07-10T18:07:53Z 47178 
200 2018-07-10T18:07:57Z 47177 
</details><br/>
or the same for /v2/recipes:<br/>
<br/>
<details>
<summary>Resulting Output /v2/recipes</summary>

200 2018-07-10T17:45:59Z 10437 
200 2018-07-10T17:46:02Z 10437 
200 2018-07-10T17:46:05Z 10437 
200 2018-07-10T17:46:09Z 10438 
200 2018-07-10T17:46:12Z 10437 
200 2018-07-10T17:46:15Z 10437 
200 2018-07-10T17:46:18Z 10438 
200 2018-07-10T17:46:21Z 10438 
200 2018-07-10T17:46:25Z 10437 
200 2018-07-10T17:46:28Z 10437 
200 2018-07-10T17:46:31Z 10438 
200 2018-07-10T17:46:34Z 10437 
200 2018-07-10T17:46:38Z 10437 
200 2018-07-10T17:46:41Z 10438 
200 2018-07-10T17:46:44Z 10437 
200 2018-07-10T17:46:47Z 10437 
200 2018-07-10T17:46:51Z 10438 
200 2018-07-10T17:46:54Z 10437 
200 2018-07-10T17:46:57Z 10438 
200 2018-07-10T17:47:00Z 10437 
200 2018-07-10T17:47:03Z 10437 
200 2018-07-10T17:47:07Z 10438 
200 2018-07-10T17:47:10Z 10437 
200 2018-07-10T17:47:13Z 10437 
200 2018-07-10T17:47:16Z 10437 
200 2018-07-10T17:47:20Z 10437 
200 2018-07-10T17:47:23Z 10437 
200 2018-07-10T17:47:26Z 10437 
200 2018-07-10T17:47:29Z 10437 
</details><br/>
altough this, presumably, affects all paginated Endpoints; for witch all else, i won't provide examples for.<br/>
<br/>
Needles to say; it would be great to see the Caching back in its former working state again as soon as possibly feasable.<br/>
<br/>
I'm making an assumption here that this possibly might be a sideefect of the blackout of the whitelists, as Caching seems to be broken since around that point in time; altough that's nothing more than an assumption.

**Comment by Aonwy** [comment]
Please take a look and let us know if this is still an issue, otherwise we will close it.

**Comment by CuriousCharr** [comment]
Sure thing. Will do so as soon as i can, given the API isn't on [fire/overloaded](https://status.gw2efficiency.com/) anymore by then.

I would much appreciate it if You could maybe do something about that fire by the way :)

**Comment by CuriousCharr** [comment]
Well.. that sure was a quick fix right there. Thanks about that :D

I'm sorry to have to report that it still fluctuates tough.

<details>
<summary>/v2/items</summary>

200 2018-09-18T18:16:32Z 52518
200 2018-09-18T18:16:35Z 52519
200 2018-09-18T18:16:39Z 52519
200 2018-09-18T18:16:42Z 52517
200 2018-09-18T18:16:46Z 52518
200 2018-09-18T18:16:49Z 52519
200 2018-09-18T18:16:53Z 52519
200 2018-09-18T18:16:56Z 52517
200 2018-09-18T18:17:00Z 52517
200 2018-09-18T18:17:04Z 52517
200 2018-09-18T18:17:07Z 52518
200 2018-09-18T18:17:11Z 52517
200 2018-09-18T18:17:14Z 52517
200 2018-09-18T18:17:18Z 52518
200 2018-09-18T18:17:21Z 52518
200 2018-09-18T18:17:25Z 52518
200 2018-09-18T18:17:28Z 52518
200 2018-09-18T18:17:31Z 52518
200 2018-09-18T18:17:35Z 52518
200 2018-09-18T18:17:39Z 52518
200 2018-09-18T18:17:42Z 52518
200 2018-09-18T18:17:46Z 52517
200 2018-09-18T18:17:49Z 52518
200 2018-09-18T18:17:52Z 52517
200 2018-09-18T18:17:56Z 52518
200 2018-09-18T18:17:59Z 52519
200 2018-09-18T18:18:03Z 52517
200 2018-09-18T18:18:06Z 52518
200 2018-09-18T18:18:10Z 52517
200 2018-09-18T18:18:13Z 52517
200 2018-09-18T18:18:17Z 52517
200 2018-09-18T18:18:20Z 52517
200 2018-09-18T18:18:23Z 52518
200 2018-09-18T18:18:27Z 52518
200 2018-09-18T18:18:30Z 52517
200 2018-09-18T18:18:34Z 52518
200 2018-09-18T18:18:37Z 52519
200 2018-09-18T18:18:41Z 52517
200 2018-09-18T18:18:44Z 52518
200 2018-09-18T18:18:48Z 52517
200 2018-09-18T18:18:51Z 52517
200 2018-09-18T18:18:55Z 52517
200 2018-09-18T18:18:58Z 52518
200 2018-09-18T18:19:02Z 52517
200 2018-09-18T18:19:05Z 52517
200 2018-09-18T18:19:09Z 52517
200 2018-09-18T18:19:12Z 52517
200 2018-09-18T18:19:16Z 52517
200 2018-09-18T18:19:19Z 52518
200 2018-09-18T18:19:23Z 52517
200 2018-09-18T18:19:26Z 52518
200 2018-09-18T18:19:30Z 52517
200 2018-09-18T18:19:33Z 52517
200 2018-09-18T18:19:37Z 52518
200 2018-09-18T18:19:40Z 52517
200 2018-09-18T18:19:44Z 52517
200 2018-09-18T18:19:47Z 52518
200 2018-09-18T18:19:51Z 52518
200 2018-09-18T18:19:54Z 52517
200 2018-09-18T18:19:58Z 52518
200 2018-09-18T18:20:01Z 52517
200 2018-09-18T18:20:05Z 52519
200 2018-09-18T18:20:08Z 52517
200 2018-09-18T18:20:12Z 52519
200 2018-09-18T18:20:16Z 52517
200 2018-09-18T18:20:19Z 52519
200 2018-09-18T18:20:22Z 52519
200 2018-09-18T18:20:26Z 52518
</details>
</br>
Now if you would excuse me, i would like to go do WvW for a while now :/

**Comment by CuriousCharr** [comment]
You might actually better just close it. No one cares anyway.

**Comment by Sejsel** [comment]
This still appears to be occurring, at least on /v2/items,
