### ISSUE TITLE
Mastery points for "Maguuma" disappeared out of /account/mastery/points

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#639]
Previously, on [/account/mastery/points](https://api.guildwars2.com/v2/account/mastery/points?access_token=BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041) you could read out the mastery points of both regions, "Maguuma" and "Tyria". Now, only "Tyria" is showing up, and "Maguuma" is missing ([for all API keys, as far as I can tell](https://gw2efficiency.com/account/statistics/statistics.masteryPointsMaguuma)).

**Comment by queicherius** [comment]
Possibly related to https://github.com/arenanet/api-cdi/issues/566

**Comment by ahlec** [comment]
Is there any news on this? Not having Maguuma available means that APIs can't tally up the total number of mastery points for an account.

**Comment by queicherius** [comment]
Additionally, the API is missing the mastery points for the new Icebrood Saga

**Comment by ChieftainAlex** [comment]
Apparently this started working again, I assume a fix has been pushed.

https://media.discordapp.net/attachments/384735523521953792/878751575873556580/unknown.png
