### ISSUE TITLE
Call an Endpoint delete Api-Key & no new Key could be created

### ISSUE THREAD

**Issue by Plitzz** [arenanet/api-cdi#64]
Hello There,

I was able to verify with some keys:
Once an endpoint key is called, the key is deleted and it can't also create a new key.

Please check and resolve urgently, otherwise the whole API is likely to be obsolete.

Best Regards

Markus / Plitzz

**Comment by Spaeda** [comment]
API key is delete at the second call.

First request : 
{"text":“endpoint requires authentication”}
**API Key still exist**
Second request :
{"text":“invalid key”}
**API Key was delete**

**Comment by dyanarose** [comment]
Is this for all authenticated endpoints, or just the tokeninfo endpoint that was mentioned in the forum post?

**Comment by Eearslya** [comment]
It seems to be all of them; my server queries the bank endpoint every 10 minutes and I haven't done anything else, and my API key is gone as well.

**Comment by Spaeda** [comment]
In my case I only test tokeninfo. I have no more key to test other endpoints.
But one guildmate test characters endpoint and he have same issue.

**Comment by Plitzz** [comment]
It looks as concerns all endpoints that use authentication.
From me it was tested with character, account and bank

**Comment by lye** [comment]
I believe this should be more-or-less resolved. The keys weren't being deleted, but due to a bug in the error handling code (which was hit by another, unrelated bug) a cache was corrupted and the keys disappeared.

They should reappear after ~5 minutes of no requests for the given account, if they haven't already.
