### ISSUE TITLE
Missing skins in /v2/mount/skins

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#646]
For example for the Springer, a 5-minute check shows:

- Shiverpeaks
- Starfall
- Sun Temple Gecko
- Timberland Badged

**Comment by Tolkyria** [comment]
I have set the [Property:Has mount id](https://wiki.guildwars2.com/wiki/Property:Has_mount_id) on the [Guild Wars 2 Wiki](https://wiki.guildwars2.com/wiki/) to track the missing ids. 

The result is:
- Raptor: 23 skins, 7 are missing.
- Springer: 24 skins, 7 are missing.
- Skimmer: 22 skins, 6 are missing.
- Jackal: 23 skins, 6 are missing.
- Griffon: 25 skins, 9 are missing.
- Bettle Roller: 9 skins, 7 are missing.

The missing mount skins can be found here [Template:Mount table](https://wiki.guildwars2.com/wiki/Template:Mount_table) on the wiki, where the highlighed red rows are the mounts with missing ids.
Furthermore, at the bottom are also tables displaying the setted ids.

The motivation of having all ids would allow the wiki user to grey out her/his owned mount skins and highlight the currently not owned ones; with the previously mentioned template.

Best, 
Wiki-editor Tolkyria

**Comment by queicherius** [comment]
Looks like the update got us all the IDs!
