### ISSUE TITLE
Missing endpoints in endpoint list

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#69]
`/v2/specializations` on https://api.guildwars2.com/v2 is missing, `/v2/characters/:id/equipment` and `/v2/characters/:id/inventory` are also still marked as disabled, and even though `/v2/traits-beta` is just a beta, it should probably also be there (or at least the disabled `/v2/traits`).

I guess that is still this ([source](https://forum-en.guildwars2.com/forum/community/api/Launching-inventory-endpoints/5211613)):
> [...] there's a bug in the API enumeration that incorrectly and unconditionally lists the characters inventory/equipment endpoints as disabled. We'll look to fix that at some point in the future so it shows the status of those endpoints properly.

**Comment by Eearslya** [comment]
To be fair, `/v2/specializations` did come out just an hour ago...But as soon as I'm done toying with it, I'll add it to the wiki. I can do the other changes, too.

**Comment by Eearslya** [comment]
...Sorry, I completely misread what this issue was about. Ignore me, carry on.

**Comment by lye** [comment]
Ah yeah, I totally forgot about this. I've been neglecting that meta-endpoint for awhile.

**Comment by lye** [comment]
Should be fixed.
