### ISSUE TITLE
Node OAuth Example Broken?

### ISSUE THREAD

**Issue by madou** [arenanet/api-cdi#70]
https://github.com/arenanet/api-cdi/tree/master/examples/auth-nodejs

Running through this I'm receiving an error after logging in, after being directed to the gw2 site.

![image](https://cloud.githubusercontent.com/assets/6801309/9006489/1e8e1914-37cb-11e5-81cd-310f0ed617f8.png)

Url:
https://account.arena.net/oauth2/authorization?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth2%2Fcallback&response_type=code&scope=account%20offline&client_id=gw2_api_demo

(Between step 5 and step 6).

Cheers,
Michael

**Comment by Coffee4cr** [comment]
OAuth has been dropped

**Comment by darthmaim** [comment]
OAuth was disabled. You now need API keys for authentication. Take a look at the [announcement](https://forum-en.guildwars2.com/forum/community/api/HEADS-UP-OAuth2-being-replaced-next-week/5025287) for more infos.

**Comment by tivac** [comment]
:skull:
