### ISSUE TITLE
Add cache expiration headers

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#73]
As per [this thread](https://forum-en.guildwars2.com/forum/community/api/Api-Caching), it would be useful if we added the configured per-endpoint cache times in the appropriate headers (currently we return no cache directives, iirc).

**Comment by tivac** [comment]
Working on this, every endpoint should return a `Cache-Control` and `Expires` header. It's not smart, but it'll tell you what you need.

**Comment by lye** [comment]
Deployed these yesterday! :D
