### ISSUE TITLE
v2/specializations icons image quality

### ISSUE THREAD

**Issue by KelianB** [arenanet/api-cdi#76]
I don't know what's up with that, but the icons for specializations don't look very good.

In-game screenshot sample:
http://i.imgur.com/r7Eepsa.png
Icon from the API:
https://render.guildwars2.com/file/F8A95D6D3904A1F6430CF2D33A02FDF2A6132037/1011997.png

Edit: there is also a silly 5-pixels gap on the left and right of the images, maybe something can be done about that too?

**Comment by darthmaim** [comment]
For easier comparison: 

Screenshot | API
----------------|------
![image](https://cloud.githubusercontent.com/assets/2511547/9089676/ae3598a2-3b96-11e5-87cc-18de89a9d883.png) | ![image](https://cloud.githubusercontent.com/assets/2511547/9089695/bc981fdc-3b96-11e5-9c1c-61378c400359.png)

**Comment by dr-ishmael** [comment]
The specializations panel in-game looks like it uses an overlay on the background image - so that's the full background image showing through with a bit of a border applied.

The icon, as referenced by the API, is what's shown in the drop-down list where you change the selected specialization.

**Comment by KelianB** [comment]
Oh yea, that makes sense! 
Then I think it would be really cool if we could have the background image for specializations.

**Comment by lye** [comment]
I can add in the backgrounds, but they're a bit wonky --

![1784571](https://cloud.githubusercontent.com/assets/921652/9091798/031d7f14-3b57-11e5-91e6-bcb327b3160c.png)

**Comment by KelianB** [comment]
If all of the backgrounds have this exact same issue, it's pretty easy to handle on our side. It would be better than nothing I guess.

**Comment by lye** [comment]
They mostly have the same issue. Pretty sure the padding dimensions are all the same, but the rgba of the padding varies. Shouldn't be a big deal.

I need to do a live deploy today to correct some discovered issues in `/v2/traits-beta`, so this change will probably go out today too <3

**Comment by lye** [comment]
Backgrounds are up. They're a bit weird; the game renders them by upscaling the image to 1024x256px, then cropping it to the lower-left 647x136px. I should probably put that in the endpoint docs. Here's an example rendering in my terrible javascript:

https://jsfiddle.net/o1oavwsa/ 

Some of them look kind of gross, but @tivac assures me that the browser image scaling is just terrible. Those are what are displayed in-game, so I don't know if there's anything I can do about that :/

**Comment by tivac** [comment]
https://developer.mozilla.org/en/docs/Web/CSS/image-rendering

Not the complete answer (compatibility lolololol), but futzing w/ these values should definitely help.

**Comment by darthmaim** [comment]
I made a [quick test resizing them on the server](https://jsfiddle.net/ayf6725p/2/), which looks slightly better, but not much, even after playing quite a bit with different filters. Especially on my retina display all those upscaled images look horrible.
But still better than nothing, thanks for the super quick fix! :heart:

**Comment by lye** [comment]
I don't even know how we're making it look this crisp in-game though:

![spec-in-game](https://cloud.githubusercontent.com/assets/921652/9099461/b73fdcca-3b85-11e5-9958-ae0deebe4e22.png)

Here's what it looks like in-browser:

![spec-in-browser](https://cloud.githubusercontent.com/assets/921652/9099473/c84f95aa-3b85-11e5-908f-966d57602208.png)

And with your server's resampling:

![spec-resampled](https://cloud.githubusercontent.com/assets/921652/9099488/e577a3a2-3b85-11e5-858c-69efb70efa17.png)

qq

**Comment by lye** [comment]
So I pulled over an engine programmer and he pointed out that we may actually be returning the correct texture but the wrong mipmap level. It's kind of telling that the bad backgrounds are exactly half the resolution of the normal ones.

The game is definitely using a different bitmap than what the render endpoint is returning though, so the inconsistency is more than just an issue with the browser's resampling. Gonna see if I can figure out how to get the correct image out.

**Comment by KelianB** [comment]
To me, some of the backgrounds have a much better quality than others. Looking at your initial jsfiddle, warrior/guardian/thief/engineer/elementalist seem better than mesmer/necromancer/ranger.
Maybe that's just me though.

**Comment by lye** [comment]
Yeah, there's some really horribly obscure bug in render.guildwars2.com that's causing it to return the first mip level of images that have embedded mipmaps.

**Comment by darthmaim** [comment]
Just had a quick look at this again, and it seems like the file ids are wrong? The API returns `1012057`, which is the 512x128 version, the correct 1024x256 one would be `1012058` (notice how it seems to always be +1 the small one). Not sure if the really is a bug with render.guildwars2.com then, maybe it's just your code getting the wrong file id (but then again, I have no idea how its stored internally).

**1012057** | ![1012057](https://cloud.githubusercontent.com/assets/2511547/9121889/976bd09c-3c85-11e5-8673-6181a863a027.png)
:------|:-----
**1012058** | ![1012058](https://cloud.githubusercontent.com/assets/2511547/9121892/9eee593e-3c85-11e5-88f4-65c215aa4d1b.png)

**Comment by lye** [comment]
Hilariously, this is partially fixed. Three of the mesmer specialization backgrounds are still broken, but the rest look like they're being returned full-res. I'll try to apply the fix again to the mesmer art and see if that finally sticks.

**Comment by lye** [comment]
Pretty sure these are all fixed.

**Comment by darthmaim** [comment]
I was hoping your fix for this would also fix some of the item icons that are returned in lower resolutions (like [222822](https://render.guildwars2.com/file/5C0ABA341AC4DB11060533EA280BEC5D3EDB9EE6/222822.png) of [Experience Scroll](https://api.guildwars2.com/v2/items/43765)). Could you maybe take a quick look if this is somehow related and could be fixed the same way?
