### ISSUE TITLE
Creating an API key in the Baidu Browser fails

### ISSUE THREAD

**Issue by iamdansker** [arenanet/api-cdi#86]
One of my users was unable to create an API key, which i found to be caused due to his use of the Baidu Browser.

It seems that when using the Baidu Browser, the request made when trying to create an API key is malformed.

I am not sure which side this problem is at, but i looked at the request in Fiddler and found that the Content-Type is set to application/x-www-form-urlencoded instead of application/json; charset=UTF-8 (as with chrome), changing this and replaying the request created the API key successfully

Idk how many even use that browser, just figured i would report it

**Comment by lye** [comment]
I mean, we're [expressly setting application/json](https://github.com/lhorie/mithril/blob/master/mithril.js#L1072) as the Content-Type (and the backend treats both differently, IIRC), so I'm not sure we'd want to fix this one. Our officially-supported browser list is IE9+, Chrome and Firefox; I'd recommend using one of those in general  :<
