### ISSUE TITLE
v2/currencies is missing language awareness indication on overview page

### ISSUE THREAD

**Issue by Teranas** [arenanet/api-cdi#92]
Hey there,

that's really a minor issue, but I noticed that the language awareness indication ([l]) is missing for the endpoint 'v2/currencies' on the overview page.

You may want to fix this ... or not ... Most people won't care :P

**Comment by darthmaim** [comment]
/v2/traits, /v2/traits-beta and /v2/specializations are missing it too.

**Comment by tivac** [comment]
We really need to rework that page to be more useful. :unamused: Thanks for the heads-up everyone!

**Comment by lye** [comment]
Should be fixed on live as of yesterday.
