### ISSUE TITLE
ErrBadData on /v2/account and /v2/characters endpoints for some apikeys

### ISSUE THREAD

**Issue by shrykull** [arenanet/api-cdi#97]
Hi, 

i got several api keys from an account that only generates keys with the following property:

/v2/tokeninfo tells me those keys got all eight availible permissions, but the following api endpoints return a HTTP 400 with text "ErrBadData":
- /v2/account/bank, 
- /v2/characters, 
- /v2/account, 
- /v2/account/wallet

i assume it has something to do with the account moving from EU to NA about three days ago, as most the information that is shared between EU and NA anyways works well. This means i get a HTTP 200 and useful data from the following api endpoints:
- /v2/commerce/transactions, 
- /v2/pvp, 
- /v2/tokeninfo
- /v2/skins

This happens to *all* the keys generated by that account (the account is not not mine, i just happened to experiment with the api keys).

i'm 100% sure i use the api correctly as the very same script works with other api keys. its just that single account that causes bugs.. 

i kind of don't want to publish any information about the account without the owner agreeing so ill eventually add his info later once he confirms.
It would be nice to see a confirmation of the devs if this is a known bug as i was not able to find anything related.

PS: Great work, the game is amazing and with the API i get an even more detailed view of it :)

**Comment by tivac** [comment]
Sounds totally possible for a key to break after a datacenter transfer. We'll investigate.

**Comment by lye** [comment]
irk, will have to look at this tomorrow. Assuming it's a shard transfer issue I *should* be able to repro it on live.

**Comment by shrykull** [comment]
I should add to this that one of the tested keys is way newer than the region change. it was made two days after the move, so maybe its not just the api but an account issue, maybe this helps you finding the bug.

**Comment by lye** [comment]
The server team found the issue -- there's a cache incoherency. They flushed all the caches for now (so previously-broken API keys should work again) but transfers will still bug the account until we've got a more permanent fix in place. Sorry about the mess, we'll have it fixed in a month or so maybe.

**Comment by shrykull** [comment]
Well, as of now, none of the keys i got here work. So i assume there might be another issue. 
But it's nice to know that this actually helped finding a bug.
