### ISSUE TITLE
https://api.guildwars2.com/v2/achievements?page=0

### ISSUE THREAD

**Issue by Coffee4cr** [arenanet/api-cdi#99]
This doesn't seem to bring up Today's objective/dailies

I'm looking at https://wiki.guildwars2.com/wiki/Daily/Table  and Today we are the 8th, and today's daily afaik are the ones listed on the 9th.

But neither one are what https://api.guildwars2.com/v2/achievements?page=0  returns.

**Comment by dr-ishmael** [comment]
The wiki is perpetually playing catch-up because Anet has been messing
around with the dailies so much lately. In this case, unfortunately, I have
to say: don't trust the wiki.

**Comment by lye** [comment]
They're not really being messed around with. They're on a rotation. The rotation's period is 366 days or so.

It's definitely possible that the API doesn't behave correctly around rollover (e.g., it might display yesterday's dailies) -- my hands have been pretty full as of late, so I haven't had time to test my implementation as thoroughly as I'd have liked.

**Comment by dr-ishmael** [comment]
What I meant was that the daily achievements have been changed up multiple
times in the past 6 months or so. There are a couple wiki editors who do
their best to keep up with these changes and update the wiki with the new
rotations, but even they are getting a little burned out at this point.

And you say the rotation is a full year long? Yeah, the wiki's not gonna
have that fully documented anytime soon...

**Comment by lye** [comment]
> What I meant was that the daily achievements have been changed up multiple times in the past 6 months or so.

Ah yeah, that's true. I'm honestly not sure if the current rotation will remain as-is, which is why the endpoint only dumps out today's dailies. For example, if seasonal dailies are coming back (e.g., for Halloween/Wintersday) they're not currently in the live data so if we returned future dailies they'd probably be wrong (same deal with past dailies -- the rotation changes don't preserve old rotations).

**Comment by lye** [comment]
Pretty sure this one is resolved.
